/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  getAddressFromResolvedInstructionAccount,
  getNonNullResolvedInstructionInput,
  type ResolvedInstructionAccount,
} from "@solana/kit/program-client-core";
import { findCheckinPda, findConfigPda } from "../pdas/index.ts";
import { EMPOWERFI_AUDIT_PROGRAM_ADDRESS } from "../programs/index.ts";

export const ANCHOR_CHECKIN_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
  231, 111, 38, 124, 230, 131, 22, 219,
]);

export function getAnchorCheckinDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    ANCHOR_CHECKIN_DISCRIMINATOR,
  );
}

export type AnchorCheckinInstruction<
  TProgram extends string = typeof EMPOWERFI_AUDIT_PROGRAM_ADDRESS,
  TAccountOperator extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountBorrower extends string | AccountMeta<string> = string,
  TAccountCheckin extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountOperator extends string
        ? WritableSignerAccount<TAccountOperator> &
            AccountSignerMeta<TAccountOperator>
        : TAccountOperator,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountBorrower extends string
        ? ReadonlyAccount<TAccountBorrower>
        : TAccountBorrower,
      TAccountCheckin extends string
        ? WritableAccount<TAccountCheckin>
        : TAccountCheckin,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type AnchorCheckinInstructionData = {
  discriminator: ReadonlyUint8Array;
  period: number;
  commitment: ReadonlyUint8Array;
};

export type AnchorCheckinInstructionDataArgs = {
  period: number;
  commitment: ReadonlyUint8Array;
};

export function getAnchorCheckinInstructionDataEncoder(): FixedSizeEncoder<AnchorCheckinInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["period", getU32Encoder()],
      ["commitment", fixEncoderSize(getBytesEncoder(), 32)],
    ]),
    (value) => ({ ...value, discriminator: ANCHOR_CHECKIN_DISCRIMINATOR }),
  );
}

export function getAnchorCheckinInstructionDataDecoder(): FixedSizeDecoder<AnchorCheckinInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["period", getU32Decoder()],
    ["commitment", fixDecoderSize(getBytesDecoder(), 32)],
  ]);
}

export function getAnchorCheckinInstructionDataCodec(): FixedSizeCodec<
  AnchorCheckinInstructionDataArgs,
  AnchorCheckinInstructionData
> {
  return combineCodec(
    getAnchorCheckinInstructionDataEncoder(),
    getAnchorCheckinInstructionDataDecoder(),
  );
}

export type AnchorCheckinAsyncInput<
  TAccountOperator extends string = string,
  TAccountConfig extends string = string,
  TAccountBorrower extends string = string,
  TAccountCheckin extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  operator: TransactionSigner<TAccountOperator>;
  config?: Address<TAccountConfig>;
  borrower: Address<TAccountBorrower>;
  checkin?: Address<TAccountCheckin>;
  systemProgram?: Address<TAccountSystemProgram>;
  period: AnchorCheckinInstructionDataArgs["period"];
  commitment: AnchorCheckinInstructionDataArgs["commitment"];
};

export async function getAnchorCheckinInstructionAsync<
  TAccountOperator extends string,
  TAccountConfig extends string,
  TAccountBorrower extends string,
  TAccountCheckin extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof EMPOWERFI_AUDIT_PROGRAM_ADDRESS,
>(
  input: AnchorCheckinAsyncInput<
    TAccountOperator,
    TAccountConfig,
    TAccountBorrower,
    TAccountCheckin,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  AnchorCheckinInstruction<
    TProgramAddress,
    TAccountOperator,
    TAccountConfig,
    TAccountBorrower,
    TAccountCheckin,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? EMPOWERFI_AUDIT_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    operator: { value: input.operator ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    borrower: { value: input.borrower ?? null, isWritable: false },
    checkin: { value: input.checkin ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.config.value) {
    accounts.config.value = await findConfigPda({ programAddress });
  }
  if (!accounts.checkin.value) {
    accounts.checkin.value = await findCheckinPda(
      {
        borrower: getAddressFromResolvedInstructionAccount(
          "borrower",
          accounts.borrower.value,
        ),
        period: getNonNullResolvedInstructionInput("period", args.period),
      },
      { programAddress },
    );
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("operator", accounts.operator),
      getAccountMeta("config", accounts.config),
      getAccountMeta("borrower", accounts.borrower),
      getAccountMeta("checkin", accounts.checkin),
      getAccountMeta("systemProgram", accounts.systemProgram),
    ],
    data: getAnchorCheckinInstructionDataEncoder().encode(
      args as AnchorCheckinInstructionDataArgs,
    ),
    programAddress,
  } as AnchorCheckinInstruction<
    TProgramAddress,
    TAccountOperator,
    TAccountConfig,
    TAccountBorrower,
    TAccountCheckin,
    TAccountSystemProgram
  >);
}

export type AnchorCheckinInput<
  TAccountOperator extends string = string,
  TAccountConfig extends string = string,
  TAccountBorrower extends string = string,
  TAccountCheckin extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  operator: TransactionSigner<TAccountOperator>;
  config: Address<TAccountConfig>;
  borrower: Address<TAccountBorrower>;
  checkin: Address<TAccountCheckin>;
  systemProgram?: Address<TAccountSystemProgram>;
  period: AnchorCheckinInstructionDataArgs["period"];
  commitment: AnchorCheckinInstructionDataArgs["commitment"];
};

export function getAnchorCheckinInstruction<
  TAccountOperator extends string,
  TAccountConfig extends string,
  TAccountBorrower extends string,
  TAccountCheckin extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof EMPOWERFI_AUDIT_PROGRAM_ADDRESS,
>(
  input: AnchorCheckinInput<
    TAccountOperator,
    TAccountConfig,
    TAccountBorrower,
    TAccountCheckin,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): AnchorCheckinInstruction<
  TProgramAddress,
  TAccountOperator,
  TAccountConfig,
  TAccountBorrower,
  TAccountCheckin,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? EMPOWERFI_AUDIT_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    operator: { value: input.operator ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    borrower: { value: input.borrower ?? null, isWritable: false },
    checkin: { value: input.checkin ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("operator", accounts.operator),
      getAccountMeta("config", accounts.config),
      getAccountMeta("borrower", accounts.borrower),
      getAccountMeta("checkin", accounts.checkin),
      getAccountMeta("systemProgram", accounts.systemProgram),
    ],
    data: getAnchorCheckinInstructionDataEncoder().encode(
      args as AnchorCheckinInstructionDataArgs,
    ),
    programAddress,
  } as AnchorCheckinInstruction<
    TProgramAddress,
    TAccountOperator,
    TAccountConfig,
    TAccountBorrower,
    TAccountCheckin,
    TAccountSystemProgram
  >);
}

export type ParsedAnchorCheckinInstruction<
  TProgram extends string = typeof EMPOWERFI_AUDIT_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    operator: TAccountMetas[0];
    config: TAccountMetas[1];
    borrower: TAccountMetas[2];
    checkin: TAccountMetas[3];
    systemProgram: TAccountMetas[4];
  };
  data: AnchorCheckinInstructionData;
};

export function parseAnchorCheckinInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedAnchorCheckinInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 5) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 5,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      operator: getNextAccount(),
      config: getNextAccount(),
      borrower: getNextAccount(),
      checkin: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getAnchorCheckinInstructionDataDecoder().decode(instruction.data),
  };
}
