/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  getAddressFromResolvedInstructionAccount,
  getNonNullResolvedInstructionInput,
  type ResolvedInstructionAccount,
} from "@solana/kit/program-client-core";
import { findConfigPda, findOutcomePda } from "../pdas/index.ts";
import { EMPOWERFI_AUDIT_PROGRAM_ADDRESS } from "../programs/index.ts";

export const ANCHOR_OUTCOME_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
  252, 143, 166, 43, 172, 223, 25, 13,
]);

export function getAnchorOutcomeDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    ANCHOR_OUTCOME_DISCRIMINATOR,
  );
}

export type AnchorOutcomeInstruction<
  TProgram extends string = typeof EMPOWERFI_AUDIT_PROGRAM_ADDRESS,
  TAccountOperator extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountLoan extends string | AccountMeta<string> = string,
  TAccountOutcome extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountOperator extends string
        ? WritableSignerAccount<TAccountOperator> &
            AccountSignerMeta<TAccountOperator>
        : TAccountOperator,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountLoan extends string
        ? ReadonlyAccount<TAccountLoan>
        : TAccountLoan,
      TAccountOutcome extends string
        ? WritableAccount<TAccountOutcome>
        : TAccountOutcome,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type AnchorOutcomeInstructionData = {
  discriminator: ReadonlyUint8Array;
  outcomeNo: number;
  commitment: ReadonlyUint8Array;
};

export type AnchorOutcomeInstructionDataArgs = {
  outcomeNo: number;
  commitment: ReadonlyUint8Array;
};

export function getAnchorOutcomeInstructionDataEncoder(): FixedSizeEncoder<AnchorOutcomeInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["outcomeNo", getU16Encoder()],
      ["commitment", fixEncoderSize(getBytesEncoder(), 32)],
    ]),
    (value) => ({ ...value, discriminator: ANCHOR_OUTCOME_DISCRIMINATOR }),
  );
}

export function getAnchorOutcomeInstructionDataDecoder(): FixedSizeDecoder<AnchorOutcomeInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["outcomeNo", getU16Decoder()],
    ["commitment", fixDecoderSize(getBytesDecoder(), 32)],
  ]);
}

export function getAnchorOutcomeInstructionDataCodec(): FixedSizeCodec<
  AnchorOutcomeInstructionDataArgs,
  AnchorOutcomeInstructionData
> {
  return combineCodec(
    getAnchorOutcomeInstructionDataEncoder(),
    getAnchorOutcomeInstructionDataDecoder(),
  );
}

export type AnchorOutcomeAsyncInput<
  TAccountOperator extends string = string,
  TAccountConfig extends string = string,
  TAccountLoan extends string = string,
  TAccountOutcome extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  operator: TransactionSigner<TAccountOperator>;
  config?: Address<TAccountConfig>;
  loan: Address<TAccountLoan>;
  outcome?: Address<TAccountOutcome>;
  systemProgram?: Address<TAccountSystemProgram>;
  outcomeNo: AnchorOutcomeInstructionDataArgs["outcomeNo"];
  commitment: AnchorOutcomeInstructionDataArgs["commitment"];
};

export async function getAnchorOutcomeInstructionAsync<
  TAccountOperator extends string,
  TAccountConfig extends string,
  TAccountLoan extends string,
  TAccountOutcome extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof EMPOWERFI_AUDIT_PROGRAM_ADDRESS,
>(
  input: AnchorOutcomeAsyncInput<
    TAccountOperator,
    TAccountConfig,
    TAccountLoan,
    TAccountOutcome,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  AnchorOutcomeInstruction<
    TProgramAddress,
    TAccountOperator,
    TAccountConfig,
    TAccountLoan,
    TAccountOutcome,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? EMPOWERFI_AUDIT_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    operator: { value: input.operator ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    loan: { value: input.loan ?? null, isWritable: false },
    outcome: { value: input.outcome ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.config.value) {
    accounts.config.value = await findConfigPda({ programAddress });
  }
  if (!accounts.outcome.value) {
    accounts.outcome.value = await findOutcomePda(
      {
        loan: getAddressFromResolvedInstructionAccount(
          "loan",
          accounts.loan.value,
        ),
        outcomeNo: getNonNullResolvedInstructionInput(
          "outcomeNo",
          args.outcomeNo,
        ),
      },
      { programAddress },
    );
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("operator", accounts.operator),
      getAccountMeta("config", accounts.config),
      getAccountMeta("loan", accounts.loan),
      getAccountMeta("outcome", accounts.outcome),
      getAccountMeta("systemProgram", accounts.systemProgram),
    ],
    data: getAnchorOutcomeInstructionDataEncoder().encode(
      args as AnchorOutcomeInstructionDataArgs,
    ),
    programAddress,
  } as AnchorOutcomeInstruction<
    TProgramAddress,
    TAccountOperator,
    TAccountConfig,
    TAccountLoan,
    TAccountOutcome,
    TAccountSystemProgram
  >);
}

export type AnchorOutcomeInput<
  TAccountOperator extends string = string,
  TAccountConfig extends string = string,
  TAccountLoan extends string = string,
  TAccountOutcome extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  operator: TransactionSigner<TAccountOperator>;
  config: Address<TAccountConfig>;
  loan: Address<TAccountLoan>;
  outcome: Address<TAccountOutcome>;
  systemProgram?: Address<TAccountSystemProgram>;
  outcomeNo: AnchorOutcomeInstructionDataArgs["outcomeNo"];
  commitment: AnchorOutcomeInstructionDataArgs["commitment"];
};

export function getAnchorOutcomeInstruction<
  TAccountOperator extends string,
  TAccountConfig extends string,
  TAccountLoan extends string,
  TAccountOutcome extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof EMPOWERFI_AUDIT_PROGRAM_ADDRESS,
>(
  input: AnchorOutcomeInput<
    TAccountOperator,
    TAccountConfig,
    TAccountLoan,
    TAccountOutcome,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): AnchorOutcomeInstruction<
  TProgramAddress,
  TAccountOperator,
  TAccountConfig,
  TAccountLoan,
  TAccountOutcome,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? EMPOWERFI_AUDIT_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    operator: { value: input.operator ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    loan: { value: input.loan ?? null, isWritable: false },
    outcome: { value: input.outcome ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("operator", accounts.operator),
      getAccountMeta("config", accounts.config),
      getAccountMeta("loan", accounts.loan),
      getAccountMeta("outcome", accounts.outcome),
      getAccountMeta("systemProgram", accounts.systemProgram),
    ],
    data: getAnchorOutcomeInstructionDataEncoder().encode(
      args as AnchorOutcomeInstructionDataArgs,
    ),
    programAddress,
  } as AnchorOutcomeInstruction<
    TProgramAddress,
    TAccountOperator,
    TAccountConfig,
    TAccountLoan,
    TAccountOutcome,
    TAccountSystemProgram
  >);
}

export type ParsedAnchorOutcomeInstruction<
  TProgram extends string = typeof EMPOWERFI_AUDIT_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    operator: TAccountMetas[0];
    config: TAccountMetas[1];
    loan: TAccountMetas[2];
    outcome: TAccountMetas[3];
    systemProgram: TAccountMetas[4];
  };
  data: AnchorOutcomeInstructionData;
};

export function parseAnchorOutcomeInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedAnchorOutcomeInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 5) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 5,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      operator: getNextAccount(),
      config: getNextAccount(),
      loan: getNextAccount(),
      outcome: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getAnchorOutcomeInstructionDataDecoder().decode(instruction.data),
  };
}
