/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  getAddressFromResolvedInstructionAccount,
  type ResolvedInstructionAccount,
} from "@solana/kit/program-client-core";
import { findConfigPda, findSettlementRoutePda } from "../pdas/index.ts";
import { EMPOWERFI_AUDIT_PROGRAM_ADDRESS } from "../programs/index.ts";
import {
  getSettlementRouteDecoder,
  getSettlementRouteEncoder,
  type SettlementRoute,
  type SettlementRouteArgs,
} from "../types/index.ts";

export const ANCHOR_SETTLEMENT_ROUTE_DISCRIMINATOR: ReadonlyUint8Array =
  new Uint8Array([175, 161, 138, 78, 92, 47, 45, 117]);

export function getAnchorSettlementRouteDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    ANCHOR_SETTLEMENT_ROUTE_DISCRIMINATOR,
  );
}

export type AnchorSettlementRouteInstruction<
  TProgram extends string = typeof EMPOWERFI_AUDIT_PROGRAM_ADDRESS,
  TAccountOperator extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountLoan extends string | AccountMeta<string> = string,
  TAccountSettlementRoute extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountOperator extends string
        ? WritableSignerAccount<TAccountOperator> &
            AccountSignerMeta<TAccountOperator>
        : TAccountOperator,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountLoan extends string
        ? ReadonlyAccount<TAccountLoan>
        : TAccountLoan,
      TAccountSettlementRoute extends string
        ? WritableAccount<TAccountSettlementRoute>
        : TAccountSettlementRoute,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type AnchorSettlementRouteInstructionData = {
  discriminator: ReadonlyUint8Array;
  route: SettlementRoute;
  commitment: ReadonlyUint8Array;
};

export type AnchorSettlementRouteInstructionDataArgs = {
  route: SettlementRouteArgs;
  commitment: ReadonlyUint8Array;
};

export function getAnchorSettlementRouteInstructionDataEncoder(): FixedSizeEncoder<AnchorSettlementRouteInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["route", getSettlementRouteEncoder()],
      ["commitment", fixEncoderSize(getBytesEncoder(), 32)],
    ]),
    (value) => ({
      ...value,
      discriminator: ANCHOR_SETTLEMENT_ROUTE_DISCRIMINATOR,
    }),
  );
}

export function getAnchorSettlementRouteInstructionDataDecoder(): FixedSizeDecoder<AnchorSettlementRouteInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["route", getSettlementRouteDecoder()],
    ["commitment", fixDecoderSize(getBytesDecoder(), 32)],
  ]);
}

export function getAnchorSettlementRouteInstructionDataCodec(): FixedSizeCodec<
  AnchorSettlementRouteInstructionDataArgs,
  AnchorSettlementRouteInstructionData
> {
  return combineCodec(
    getAnchorSettlementRouteInstructionDataEncoder(),
    getAnchorSettlementRouteInstructionDataDecoder(),
  );
}

export type AnchorSettlementRouteAsyncInput<
  TAccountOperator extends string = string,
  TAccountConfig extends string = string,
  TAccountLoan extends string = string,
  TAccountSettlementRoute extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  operator: TransactionSigner<TAccountOperator>;
  config?: Address<TAccountConfig>;
  loan: Address<TAccountLoan>;
  settlementRoute?: Address<TAccountSettlementRoute>;
  systemProgram?: Address<TAccountSystemProgram>;
  route: AnchorSettlementRouteInstructionDataArgs["route"];
  commitment: AnchorSettlementRouteInstructionDataArgs["commitment"];
};

export async function getAnchorSettlementRouteInstructionAsync<
  TAccountOperator extends string,
  TAccountConfig extends string,
  TAccountLoan extends string,
  TAccountSettlementRoute extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof EMPOWERFI_AUDIT_PROGRAM_ADDRESS,
>(
  input: AnchorSettlementRouteAsyncInput<
    TAccountOperator,
    TAccountConfig,
    TAccountLoan,
    TAccountSettlementRoute,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  AnchorSettlementRouteInstruction<
    TProgramAddress,
    TAccountOperator,
    TAccountConfig,
    TAccountLoan,
    TAccountSettlementRoute,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? EMPOWERFI_AUDIT_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    operator: { value: input.operator ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    loan: { value: input.loan ?? null, isWritable: false },
    settlementRoute: { value: input.settlementRoute ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.config.value) {
    accounts.config.value = await findConfigPda({ programAddress });
  }
  if (!accounts.settlementRoute.value) {
    accounts.settlementRoute.value = await findSettlementRoutePda(
      {
        loan: getAddressFromResolvedInstructionAccount(
          "loan",
          accounts.loan.value,
        ),
      },
      { programAddress },
    );
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("operator", accounts.operator),
      getAccountMeta("config", accounts.config),
      getAccountMeta("loan", accounts.loan),
      getAccountMeta("settlementRoute", accounts.settlementRoute),
      getAccountMeta("systemProgram", accounts.systemProgram),
    ],
    data: getAnchorSettlementRouteInstructionDataEncoder().encode(
      args as AnchorSettlementRouteInstructionDataArgs,
    ),
    programAddress,
  } as AnchorSettlementRouteInstruction<
    TProgramAddress,
    TAccountOperator,
    TAccountConfig,
    TAccountLoan,
    TAccountSettlementRoute,
    TAccountSystemProgram
  >);
}

export type AnchorSettlementRouteInput<
  TAccountOperator extends string = string,
  TAccountConfig extends string = string,
  TAccountLoan extends string = string,
  TAccountSettlementRoute extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  operator: TransactionSigner<TAccountOperator>;
  config: Address<TAccountConfig>;
  loan: Address<TAccountLoan>;
  settlementRoute: Address<TAccountSettlementRoute>;
  systemProgram?: Address<TAccountSystemProgram>;
  route: AnchorSettlementRouteInstructionDataArgs["route"];
  commitment: AnchorSettlementRouteInstructionDataArgs["commitment"];
};

export function getAnchorSettlementRouteInstruction<
  TAccountOperator extends string,
  TAccountConfig extends string,
  TAccountLoan extends string,
  TAccountSettlementRoute extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof EMPOWERFI_AUDIT_PROGRAM_ADDRESS,
>(
  input: AnchorSettlementRouteInput<
    TAccountOperator,
    TAccountConfig,
    TAccountLoan,
    TAccountSettlementRoute,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): AnchorSettlementRouteInstruction<
  TProgramAddress,
  TAccountOperator,
  TAccountConfig,
  TAccountLoan,
  TAccountSettlementRoute,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? EMPOWERFI_AUDIT_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    operator: { value: input.operator ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    loan: { value: input.loan ?? null, isWritable: false },
    settlementRoute: { value: input.settlementRoute ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("operator", accounts.operator),
      getAccountMeta("config", accounts.config),
      getAccountMeta("loan", accounts.loan),
      getAccountMeta("settlementRoute", accounts.settlementRoute),
      getAccountMeta("systemProgram", accounts.systemProgram),
    ],
    data: getAnchorSettlementRouteInstructionDataEncoder().encode(
      args as AnchorSettlementRouteInstructionDataArgs,
    ),
    programAddress,
  } as AnchorSettlementRouteInstruction<
    TProgramAddress,
    TAccountOperator,
    TAccountConfig,
    TAccountLoan,
    TAccountSettlementRoute,
    TAccountSystemProgram
  >);
}

export type ParsedAnchorSettlementRouteInstruction<
  TProgram extends string = typeof EMPOWERFI_AUDIT_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    operator: TAccountMetas[0];
    config: TAccountMetas[1];
    loan: TAccountMetas[2];
    settlementRoute: TAccountMetas[3];
    systemProgram: TAccountMetas[4];
  };
  data: AnchorSettlementRouteInstructionData;
};

export function parseAnchorSettlementRouteInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedAnchorSettlementRouteInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 5) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 5,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      operator: getNextAccount(),
      config: getNextAccount(),
      loan: getNextAccount(),
      settlementRoute: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getAnchorSettlementRouteInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
