/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  getAddressFromResolvedInstructionAccount,
  getNonNullResolvedInstructionInput,
  type ResolvedInstructionAccount,
} from "@solana/kit/program-client-core";
import { findConfigPda, findOpportunityPda } from "../pdas/index.ts";
import { EMPOWERFI_AUDIT_PROGRAM_ADDRESS } from "../programs/index.ts";

export const ANCHOR_OPPORTUNITY_DISCRIMINATOR: ReadonlyUint8Array =
  new Uint8Array([181, 6, 247, 147, 168, 144, 92, 150]);

export function getAnchorOpportunityDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    ANCHOR_OPPORTUNITY_DISCRIMINATOR,
  );
}

export type AnchorOpportunityInstruction<
  TProgram extends string = typeof EMPOWERFI_AUDIT_PROGRAM_ADDRESS,
  TAccountOperator extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountBorrower extends string | AccountMeta<string> = string,
  TAccountEligibility extends string | AccountMeta<string> = string,
  TAccountOpportunity extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountOperator extends string
        ? WritableSignerAccount<TAccountOperator> &
            AccountSignerMeta<TAccountOperator>
        : TAccountOperator,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountBorrower extends string
        ? ReadonlyAccount<TAccountBorrower>
        : TAccountBorrower,
      TAccountEligibility extends string
        ? ReadonlyAccount<TAccountEligibility>
        : TAccountEligibility,
      TAccountOpportunity extends string
        ? WritableAccount<TAccountOpportunity>
        : TAccountOpportunity,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type AnchorOpportunityInstructionData = {
  discriminator: ReadonlyUint8Array;
  opportunityNo: number;
  commitment: ReadonlyUint8Array;
};

export type AnchorOpportunityInstructionDataArgs = {
  opportunityNo: number;
  commitment: ReadonlyUint8Array;
};

export function getAnchorOpportunityInstructionDataEncoder(): FixedSizeEncoder<AnchorOpportunityInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["opportunityNo", getU32Encoder()],
      ["commitment", fixEncoderSize(getBytesEncoder(), 32)],
    ]),
    (value) => ({ ...value, discriminator: ANCHOR_OPPORTUNITY_DISCRIMINATOR }),
  );
}

export function getAnchorOpportunityInstructionDataDecoder(): FixedSizeDecoder<AnchorOpportunityInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["opportunityNo", getU32Decoder()],
    ["commitment", fixDecoderSize(getBytesDecoder(), 32)],
  ]);
}

export function getAnchorOpportunityInstructionDataCodec(): FixedSizeCodec<
  AnchorOpportunityInstructionDataArgs,
  AnchorOpportunityInstructionData
> {
  return combineCodec(
    getAnchorOpportunityInstructionDataEncoder(),
    getAnchorOpportunityInstructionDataDecoder(),
  );
}

export type AnchorOpportunityAsyncInput<
  TAccountOperator extends string = string,
  TAccountConfig extends string = string,
  TAccountBorrower extends string = string,
  TAccountEligibility extends string = string,
  TAccountOpportunity extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  operator: TransactionSigner<TAccountOperator>;
  config?: Address<TAccountConfig>;
  borrower: Address<TAccountBorrower>;
  eligibility: Address<TAccountEligibility>;
  opportunity?: Address<TAccountOpportunity>;
  systemProgram?: Address<TAccountSystemProgram>;
  opportunityNo: AnchorOpportunityInstructionDataArgs["opportunityNo"];
  commitment: AnchorOpportunityInstructionDataArgs["commitment"];
};

export async function getAnchorOpportunityInstructionAsync<
  TAccountOperator extends string,
  TAccountConfig extends string,
  TAccountBorrower extends string,
  TAccountEligibility extends string,
  TAccountOpportunity extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof EMPOWERFI_AUDIT_PROGRAM_ADDRESS,
>(
  input: AnchorOpportunityAsyncInput<
    TAccountOperator,
    TAccountConfig,
    TAccountBorrower,
    TAccountEligibility,
    TAccountOpportunity,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  AnchorOpportunityInstruction<
    TProgramAddress,
    TAccountOperator,
    TAccountConfig,
    TAccountBorrower,
    TAccountEligibility,
    TAccountOpportunity,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? EMPOWERFI_AUDIT_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    operator: { value: input.operator ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    borrower: { value: input.borrower ?? null, isWritable: false },
    eligibility: { value: input.eligibility ?? null, isWritable: false },
    opportunity: { value: input.opportunity ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.config.value) {
    accounts.config.value = await findConfigPda({ programAddress });
  }
  if (!accounts.opportunity.value) {
    accounts.opportunity.value = await findOpportunityPda(
      {
        borrower: getAddressFromResolvedInstructionAccount(
          "borrower",
          accounts.borrower.value,
        ),
        opportunityNo: getNonNullResolvedInstructionInput(
          "opportunityNo",
          args.opportunityNo,
        ),
      },
      { programAddress },
    );
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("operator", accounts.operator),
      getAccountMeta("config", accounts.config),
      getAccountMeta("borrower", accounts.borrower),
      getAccountMeta("eligibility", accounts.eligibility),
      getAccountMeta("opportunity", accounts.opportunity),
      getAccountMeta("systemProgram", accounts.systemProgram),
    ],
    data: getAnchorOpportunityInstructionDataEncoder().encode(
      args as AnchorOpportunityInstructionDataArgs,
    ),
    programAddress,
  } as AnchorOpportunityInstruction<
    TProgramAddress,
    TAccountOperator,
    TAccountConfig,
    TAccountBorrower,
    TAccountEligibility,
    TAccountOpportunity,
    TAccountSystemProgram
  >);
}

export type AnchorOpportunityInput<
  TAccountOperator extends string = string,
  TAccountConfig extends string = string,
  TAccountBorrower extends string = string,
  TAccountEligibility extends string = string,
  TAccountOpportunity extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  operator: TransactionSigner<TAccountOperator>;
  config: Address<TAccountConfig>;
  borrower: Address<TAccountBorrower>;
  eligibility: Address<TAccountEligibility>;
  opportunity: Address<TAccountOpportunity>;
  systemProgram?: Address<TAccountSystemProgram>;
  opportunityNo: AnchorOpportunityInstructionDataArgs["opportunityNo"];
  commitment: AnchorOpportunityInstructionDataArgs["commitment"];
};

export function getAnchorOpportunityInstruction<
  TAccountOperator extends string,
  TAccountConfig extends string,
  TAccountBorrower extends string,
  TAccountEligibility extends string,
  TAccountOpportunity extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof EMPOWERFI_AUDIT_PROGRAM_ADDRESS,
>(
  input: AnchorOpportunityInput<
    TAccountOperator,
    TAccountConfig,
    TAccountBorrower,
    TAccountEligibility,
    TAccountOpportunity,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): AnchorOpportunityInstruction<
  TProgramAddress,
  TAccountOperator,
  TAccountConfig,
  TAccountBorrower,
  TAccountEligibility,
  TAccountOpportunity,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? EMPOWERFI_AUDIT_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    operator: { value: input.operator ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    borrower: { value: input.borrower ?? null, isWritable: false },
    eligibility: { value: input.eligibility ?? null, isWritable: false },
    opportunity: { value: input.opportunity ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("operator", accounts.operator),
      getAccountMeta("config", accounts.config),
      getAccountMeta("borrower", accounts.borrower),
      getAccountMeta("eligibility", accounts.eligibility),
      getAccountMeta("opportunity", accounts.opportunity),
      getAccountMeta("systemProgram", accounts.systemProgram),
    ],
    data: getAnchorOpportunityInstructionDataEncoder().encode(
      args as AnchorOpportunityInstructionDataArgs,
    ),
    programAddress,
  } as AnchorOpportunityInstruction<
    TProgramAddress,
    TAccountOperator,
    TAccountConfig,
    TAccountBorrower,
    TAccountEligibility,
    TAccountOpportunity,
    TAccountSystemProgram
  >);
}

export type ParsedAnchorOpportunityInstruction<
  TProgram extends string = typeof EMPOWERFI_AUDIT_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    operator: TAccountMetas[0];
    config: TAccountMetas[1];
    borrower: TAccountMetas[2];
    eligibility: TAccountMetas[3];
    opportunity: TAccountMetas[4];
    systemProgram: TAccountMetas[5];
  };
  data: AnchorOpportunityInstructionData;
};

export function parseAnchorOpportunityInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedAnchorOpportunityInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 6) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 6,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      operator: getNextAccount(),
      config: getNextAccount(),
      borrower: getNextAccount(),
      eligibility: getNextAccount(),
      opportunity: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getAnchorOpportunityInstructionDataDecoder().decode(instruction.data),
  };
}
