/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU32Decoder,
  getU32Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  getAddressFromResolvedInstructionAccount,
  getNonNullResolvedInstructionInput,
  type ResolvedInstructionAccount,
} from "@solana/kit/program-client-core";
import { findAttestationPda, findConfigPda } from "../pdas/index.ts";
import { EMPOWERFI_AUDIT_PROGRAM_ADDRESS } from "../programs/index.ts";
import {
  getReadinessBandDecoder,
  getReadinessBandEncoder,
  getReadinessStatusDecoder,
  getReadinessStatusEncoder,
  type ReadinessBand,
  type ReadinessBandArgs,
  type ReadinessStatus,
  type ReadinessStatusArgs,
} from "../types/index.ts";

export const ATTEST_READINESS_DISCRIMINATOR: ReadonlyUint8Array =
  new Uint8Array([192, 219, 150, 110, 139, 47, 138, 18]);

export function getAttestReadinessDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    ATTEST_READINESS_DISCRIMINATOR,
  );
}

export type AttestReadinessInstruction<
  TProgram extends string = typeof EMPOWERFI_AUDIT_PROGRAM_ADDRESS,
  TAccountOperator extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountBorrower extends string | AccountMeta<string> = string,
  TAccountAttestation extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountOperator extends string
        ? WritableSignerAccount<TAccountOperator> &
            AccountSignerMeta<TAccountOperator>
        : TAccountOperator,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountBorrower extends string
        ? ReadonlyAccount<TAccountBorrower>
        : TAccountBorrower,
      TAccountAttestation extends string
        ? WritableAccount<TAccountAttestation>
        : TAccountAttestation,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type AttestReadinessInstructionData = {
  discriminator: ReadonlyUint8Array;
  assessmentNo: number;
  status: ReadinessStatus;
  band: ReadinessBand;
  modelVersion: number;
  commitment: ReadonlyUint8Array;
};

export type AttestReadinessInstructionDataArgs = {
  assessmentNo: number;
  status: ReadinessStatusArgs;
  band: ReadinessBandArgs;
  modelVersion: number;
  commitment: ReadonlyUint8Array;
};

export function getAttestReadinessInstructionDataEncoder(): FixedSizeEncoder<AttestReadinessInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["assessmentNo", getU32Encoder()],
      ["status", getReadinessStatusEncoder()],
      ["band", getReadinessBandEncoder()],
      ["modelVersion", getU16Encoder()],
      ["commitment", fixEncoderSize(getBytesEncoder(), 32)],
    ]),
    (value) => ({ ...value, discriminator: ATTEST_READINESS_DISCRIMINATOR }),
  );
}

export function getAttestReadinessInstructionDataDecoder(): FixedSizeDecoder<AttestReadinessInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["assessmentNo", getU32Decoder()],
    ["status", getReadinessStatusDecoder()],
    ["band", getReadinessBandDecoder()],
    ["modelVersion", getU16Decoder()],
    ["commitment", fixDecoderSize(getBytesDecoder(), 32)],
  ]);
}

export function getAttestReadinessInstructionDataCodec(): FixedSizeCodec<
  AttestReadinessInstructionDataArgs,
  AttestReadinessInstructionData
> {
  return combineCodec(
    getAttestReadinessInstructionDataEncoder(),
    getAttestReadinessInstructionDataDecoder(),
  );
}

export type AttestReadinessAsyncInput<
  TAccountOperator extends string = string,
  TAccountConfig extends string = string,
  TAccountBorrower extends string = string,
  TAccountAttestation extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  operator: TransactionSigner<TAccountOperator>;
  config?: Address<TAccountConfig>;
  borrower: Address<TAccountBorrower>;
  attestation?: Address<TAccountAttestation>;
  systemProgram?: Address<TAccountSystemProgram>;
  assessmentNo: AttestReadinessInstructionDataArgs["assessmentNo"];
  status: AttestReadinessInstructionDataArgs["status"];
  band: AttestReadinessInstructionDataArgs["band"];
  modelVersion: AttestReadinessInstructionDataArgs["modelVersion"];
  commitment: AttestReadinessInstructionDataArgs["commitment"];
};

export async function getAttestReadinessInstructionAsync<
  TAccountOperator extends string,
  TAccountConfig extends string,
  TAccountBorrower extends string,
  TAccountAttestation extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof EMPOWERFI_AUDIT_PROGRAM_ADDRESS,
>(
  input: AttestReadinessAsyncInput<
    TAccountOperator,
    TAccountConfig,
    TAccountBorrower,
    TAccountAttestation,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  AttestReadinessInstruction<
    TProgramAddress,
    TAccountOperator,
    TAccountConfig,
    TAccountBorrower,
    TAccountAttestation,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? EMPOWERFI_AUDIT_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    operator: { value: input.operator ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    borrower: { value: input.borrower ?? null, isWritable: false },
    attestation: { value: input.attestation ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.config.value) {
    accounts.config.value = await findConfigPda({ programAddress });
  }
  if (!accounts.attestation.value) {
    accounts.attestation.value = await findAttestationPda(
      {
        borrower: getAddressFromResolvedInstructionAccount(
          "borrower",
          accounts.borrower.value,
        ),
        assessmentNo: getNonNullResolvedInstructionInput(
          "assessmentNo",
          args.assessmentNo,
        ),
      },
      { programAddress },
    );
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("operator", accounts.operator),
      getAccountMeta("config", accounts.config),
      getAccountMeta("borrower", accounts.borrower),
      getAccountMeta("attestation", accounts.attestation),
      getAccountMeta("systemProgram", accounts.systemProgram),
    ],
    data: getAttestReadinessInstructionDataEncoder().encode(
      args as AttestReadinessInstructionDataArgs,
    ),
    programAddress,
  } as AttestReadinessInstruction<
    TProgramAddress,
    TAccountOperator,
    TAccountConfig,
    TAccountBorrower,
    TAccountAttestation,
    TAccountSystemProgram
  >);
}

export type AttestReadinessInput<
  TAccountOperator extends string = string,
  TAccountConfig extends string = string,
  TAccountBorrower extends string = string,
  TAccountAttestation extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  operator: TransactionSigner<TAccountOperator>;
  config: Address<TAccountConfig>;
  borrower: Address<TAccountBorrower>;
  attestation: Address<TAccountAttestation>;
  systemProgram?: Address<TAccountSystemProgram>;
  assessmentNo: AttestReadinessInstructionDataArgs["assessmentNo"];
  status: AttestReadinessInstructionDataArgs["status"];
  band: AttestReadinessInstructionDataArgs["band"];
  modelVersion: AttestReadinessInstructionDataArgs["modelVersion"];
  commitment: AttestReadinessInstructionDataArgs["commitment"];
};

export function getAttestReadinessInstruction<
  TAccountOperator extends string,
  TAccountConfig extends string,
  TAccountBorrower extends string,
  TAccountAttestation extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof EMPOWERFI_AUDIT_PROGRAM_ADDRESS,
>(
  input: AttestReadinessInput<
    TAccountOperator,
    TAccountConfig,
    TAccountBorrower,
    TAccountAttestation,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): AttestReadinessInstruction<
  TProgramAddress,
  TAccountOperator,
  TAccountConfig,
  TAccountBorrower,
  TAccountAttestation,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? EMPOWERFI_AUDIT_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    operator: { value: input.operator ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    borrower: { value: input.borrower ?? null, isWritable: false },
    attestation: { value: input.attestation ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("operator", accounts.operator),
      getAccountMeta("config", accounts.config),
      getAccountMeta("borrower", accounts.borrower),
      getAccountMeta("attestation", accounts.attestation),
      getAccountMeta("systemProgram", accounts.systemProgram),
    ],
    data: getAttestReadinessInstructionDataEncoder().encode(
      args as AttestReadinessInstructionDataArgs,
    ),
    programAddress,
  } as AttestReadinessInstruction<
    TProgramAddress,
    TAccountOperator,
    TAccountConfig,
    TAccountBorrower,
    TAccountAttestation,
    TAccountSystemProgram
  >);
}

export type ParsedAttestReadinessInstruction<
  TProgram extends string = typeof EMPOWERFI_AUDIT_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    operator: TAccountMetas[0];
    config: TAccountMetas[1];
    borrower: TAccountMetas[2];
    attestation: TAccountMetas[3];
    systemProgram: TAccountMetas[4];
  };
  data: AttestReadinessInstructionData;
};

export function parseAttestReadinessInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedAttestReadinessInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 5) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 5,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      operator: getNextAccount(),
      config: getNextAccount(),
      borrower: getNextAccount(),
      attestation: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getAttestReadinessInstructionDataDecoder().decode(instruction.data),
  };
}
