/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  getAddressFromResolvedInstructionAccount,
  type ResolvedInstructionAccount,
} from "@solana/kit/program-client-core";
import { findConfigPda, findLoanPda } from "../pdas/index.ts";
import { EMPOWERFI_AUDIT_PROGRAM_ADDRESS } from "../programs/index.ts";

export const CREATE_LOAN_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
  166, 131, 118, 219, 138, 218, 206, 140,
]);

export function getCreateLoanDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(CREATE_LOAN_DISCRIMINATOR);
}

export type CreateLoanInstruction<
  TProgram extends string = typeof EMPOWERFI_AUDIT_PROGRAM_ADDRESS,
  TAccountOperator extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountOpportunity extends string | AccountMeta<string> = string,
  TAccountLoan extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountOperator extends string
        ? WritableSignerAccount<TAccountOperator> &
            AccountSignerMeta<TAccountOperator>
        : TAccountOperator,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountOpportunity extends string
        ? ReadonlyAccount<TAccountOpportunity>
        : TAccountOpportunity,
      TAccountLoan extends string
        ? WritableAccount<TAccountLoan>
        : TAccountLoan,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type CreateLoanInstructionData = {
  discriminator: ReadonlyUint8Array;
  termsCommitment: ReadonlyUint8Array;
};

export type CreateLoanInstructionDataArgs = {
  termsCommitment: ReadonlyUint8Array;
};

export function getCreateLoanInstructionDataEncoder(): FixedSizeEncoder<CreateLoanInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["termsCommitment", fixEncoderSize(getBytesEncoder(), 32)],
    ]),
    (value) => ({ ...value, discriminator: CREATE_LOAN_DISCRIMINATOR }),
  );
}

export function getCreateLoanInstructionDataDecoder(): FixedSizeDecoder<CreateLoanInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["termsCommitment", fixDecoderSize(getBytesDecoder(), 32)],
  ]);
}

export function getCreateLoanInstructionDataCodec(): FixedSizeCodec<
  CreateLoanInstructionDataArgs,
  CreateLoanInstructionData
> {
  return combineCodec(
    getCreateLoanInstructionDataEncoder(),
    getCreateLoanInstructionDataDecoder(),
  );
}

export type CreateLoanAsyncInput<
  TAccountOperator extends string = string,
  TAccountConfig extends string = string,
  TAccountOpportunity extends string = string,
  TAccountLoan extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  operator: TransactionSigner<TAccountOperator>;
  config?: Address<TAccountConfig>;
  opportunity: Address<TAccountOpportunity>;
  loan?: Address<TAccountLoan>;
  systemProgram?: Address<TAccountSystemProgram>;
  termsCommitment: CreateLoanInstructionDataArgs["termsCommitment"];
};

export async function getCreateLoanInstructionAsync<
  TAccountOperator extends string,
  TAccountConfig extends string,
  TAccountOpportunity extends string,
  TAccountLoan extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof EMPOWERFI_AUDIT_PROGRAM_ADDRESS,
>(
  input: CreateLoanAsyncInput<
    TAccountOperator,
    TAccountConfig,
    TAccountOpportunity,
    TAccountLoan,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  CreateLoanInstruction<
    TProgramAddress,
    TAccountOperator,
    TAccountConfig,
    TAccountOpportunity,
    TAccountLoan,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? EMPOWERFI_AUDIT_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    operator: { value: input.operator ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    opportunity: { value: input.opportunity ?? null, isWritable: false },
    loan: { value: input.loan ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.config.value) {
    accounts.config.value = await findConfigPda({ programAddress });
  }
  if (!accounts.loan.value) {
    accounts.loan.value = await findLoanPda(
      {
        opportunity: getAddressFromResolvedInstructionAccount(
          "opportunity",
          accounts.opportunity.value,
        ),
      },
      { programAddress },
    );
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("operator", accounts.operator),
      getAccountMeta("config", accounts.config),
      getAccountMeta("opportunity", accounts.opportunity),
      getAccountMeta("loan", accounts.loan),
      getAccountMeta("systemProgram", accounts.systemProgram),
    ],
    data: getCreateLoanInstructionDataEncoder().encode(
      args as CreateLoanInstructionDataArgs,
    ),
    programAddress,
  } as CreateLoanInstruction<
    TProgramAddress,
    TAccountOperator,
    TAccountConfig,
    TAccountOpportunity,
    TAccountLoan,
    TAccountSystemProgram
  >);
}

export type CreateLoanInput<
  TAccountOperator extends string = string,
  TAccountConfig extends string = string,
  TAccountOpportunity extends string = string,
  TAccountLoan extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  operator: TransactionSigner<TAccountOperator>;
  config: Address<TAccountConfig>;
  opportunity: Address<TAccountOpportunity>;
  loan: Address<TAccountLoan>;
  systemProgram?: Address<TAccountSystemProgram>;
  termsCommitment: CreateLoanInstructionDataArgs["termsCommitment"];
};

export function getCreateLoanInstruction<
  TAccountOperator extends string,
  TAccountConfig extends string,
  TAccountOpportunity extends string,
  TAccountLoan extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof EMPOWERFI_AUDIT_PROGRAM_ADDRESS,
>(
  input: CreateLoanInput<
    TAccountOperator,
    TAccountConfig,
    TAccountOpportunity,
    TAccountLoan,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): CreateLoanInstruction<
  TProgramAddress,
  TAccountOperator,
  TAccountConfig,
  TAccountOpportunity,
  TAccountLoan,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? EMPOWERFI_AUDIT_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    operator: { value: input.operator ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    opportunity: { value: input.opportunity ?? null, isWritable: false },
    loan: { value: input.loan ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("operator", accounts.operator),
      getAccountMeta("config", accounts.config),
      getAccountMeta("opportunity", accounts.opportunity),
      getAccountMeta("loan", accounts.loan),
      getAccountMeta("systemProgram", accounts.systemProgram),
    ],
    data: getCreateLoanInstructionDataEncoder().encode(
      args as CreateLoanInstructionDataArgs,
    ),
    programAddress,
  } as CreateLoanInstruction<
    TProgramAddress,
    TAccountOperator,
    TAccountConfig,
    TAccountOpportunity,
    TAccountLoan,
    TAccountSystemProgram
  >);
}

export type ParsedCreateLoanInstruction<
  TProgram extends string = typeof EMPOWERFI_AUDIT_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    operator: TAccountMetas[0];
    config: TAccountMetas[1];
    opportunity: TAccountMetas[2];
    loan: TAccountMetas[3];
    systemProgram: TAccountMetas[4];
  };
  data: CreateLoanInstructionData;
};

export function parseCreateLoanInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedCreateLoanInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 5) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 5,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      operator: getNextAccount(),
      config: getNextAccount(),
      opportunity: getNextAccount(),
      loan: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getCreateLoanInstructionDataDecoder().decode(instruction.data),
  };
}
