/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type ResolvedInstructionAccount,
} from "@solana/kit/program-client-core";
import { findConfigPda } from "../pdas/index.ts";
import { EMPOWERFI_AUDIT_PROGRAM_ADDRESS } from "../programs/index.ts";
import {
  getLoanStatusDecoder,
  getLoanStatusEncoder,
  type LoanStatus,
  type LoanStatusArgs,
} from "../types/index.ts";

export const TRANSITION_LOAN_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array(
  [53, 30, 226, 118, 198, 154, 112, 240],
);

export function getTransitionLoanDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    TRANSITION_LOAN_DISCRIMINATOR,
  );
}

export type TransitionLoanInstruction<
  TProgram extends string = typeof EMPOWERFI_AUDIT_PROGRAM_ADDRESS,
  TAccountOperator extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountLoan extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountOperator extends string
        ? ReadonlySignerAccount<TAccountOperator> &
            AccountSignerMeta<TAccountOperator>
        : TAccountOperator,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountLoan extends string
        ? WritableAccount<TAccountLoan>
        : TAccountLoan,
      ...TRemainingAccounts,
    ]
  >;

export type TransitionLoanInstructionData = {
  discriminator: ReadonlyUint8Array;
  to: LoanStatus;
  transitionCommitment: ReadonlyUint8Array;
};

export type TransitionLoanInstructionDataArgs = {
  to: LoanStatusArgs;
  transitionCommitment: ReadonlyUint8Array;
};

export function getTransitionLoanInstructionDataEncoder(): FixedSizeEncoder<TransitionLoanInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["to", getLoanStatusEncoder()],
      ["transitionCommitment", fixEncoderSize(getBytesEncoder(), 32)],
    ]),
    (value) => ({ ...value, discriminator: TRANSITION_LOAN_DISCRIMINATOR }),
  );
}

export function getTransitionLoanInstructionDataDecoder(): FixedSizeDecoder<TransitionLoanInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["to", getLoanStatusDecoder()],
    ["transitionCommitment", fixDecoderSize(getBytesDecoder(), 32)],
  ]);
}

export function getTransitionLoanInstructionDataCodec(): FixedSizeCodec<
  TransitionLoanInstructionDataArgs,
  TransitionLoanInstructionData
> {
  return combineCodec(
    getTransitionLoanInstructionDataEncoder(),
    getTransitionLoanInstructionDataDecoder(),
  );
}

export type TransitionLoanAsyncInput<
  TAccountOperator extends string = string,
  TAccountConfig extends string = string,
  TAccountLoan extends string = string,
> = {
  operator: TransactionSigner<TAccountOperator>;
  config?: Address<TAccountConfig>;
  loan: Address<TAccountLoan>;
  to: TransitionLoanInstructionDataArgs["to"];
  transitionCommitment: TransitionLoanInstructionDataArgs["transitionCommitment"];
};

export async function getTransitionLoanInstructionAsync<
  TAccountOperator extends string,
  TAccountConfig extends string,
  TAccountLoan extends string,
  TProgramAddress extends Address = typeof EMPOWERFI_AUDIT_PROGRAM_ADDRESS,
>(
  input: TransitionLoanAsyncInput<
    TAccountOperator,
    TAccountConfig,
    TAccountLoan
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  TransitionLoanInstruction<
    TProgramAddress,
    TAccountOperator,
    TAccountConfig,
    TAccountLoan
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? EMPOWERFI_AUDIT_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    operator: { value: input.operator ?? null, isWritable: false },
    config: { value: input.config ?? null, isWritable: false },
    loan: { value: input.loan ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.config.value) {
    accounts.config.value = await findConfigPda({ programAddress });
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("operator", accounts.operator),
      getAccountMeta("config", accounts.config),
      getAccountMeta("loan", accounts.loan),
    ],
    data: getTransitionLoanInstructionDataEncoder().encode(
      args as TransitionLoanInstructionDataArgs,
    ),
    programAddress,
  } as TransitionLoanInstruction<
    TProgramAddress,
    TAccountOperator,
    TAccountConfig,
    TAccountLoan
  >);
}

export type TransitionLoanInput<
  TAccountOperator extends string = string,
  TAccountConfig extends string = string,
  TAccountLoan extends string = string,
> = {
  operator: TransactionSigner<TAccountOperator>;
  config: Address<TAccountConfig>;
  loan: Address<TAccountLoan>;
  to: TransitionLoanInstructionDataArgs["to"];
  transitionCommitment: TransitionLoanInstructionDataArgs["transitionCommitment"];
};

export function getTransitionLoanInstruction<
  TAccountOperator extends string,
  TAccountConfig extends string,
  TAccountLoan extends string,
  TProgramAddress extends Address = typeof EMPOWERFI_AUDIT_PROGRAM_ADDRESS,
>(
  input: TransitionLoanInput<TAccountOperator, TAccountConfig, TAccountLoan>,
  config?: { programAddress?: TProgramAddress },
): TransitionLoanInstruction<
  TProgramAddress,
  TAccountOperator,
  TAccountConfig,
  TAccountLoan
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? EMPOWERFI_AUDIT_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    operator: { value: input.operator ?? null, isWritable: false },
    config: { value: input.config ?? null, isWritable: false },
    loan: { value: input.loan ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("operator", accounts.operator),
      getAccountMeta("config", accounts.config),
      getAccountMeta("loan", accounts.loan),
    ],
    data: getTransitionLoanInstructionDataEncoder().encode(
      args as TransitionLoanInstructionDataArgs,
    ),
    programAddress,
  } as TransitionLoanInstruction<
    TProgramAddress,
    TAccountOperator,
    TAccountConfig,
    TAccountLoan
  >);
}

export type ParsedTransitionLoanInstruction<
  TProgram extends string = typeof EMPOWERFI_AUDIT_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    operator: TAccountMetas[0];
    config: TAccountMetas[1];
    loan: TAccountMetas[2];
  };
  data: TransitionLoanInstructionData;
};

export function parseTransitionLoanInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedTransitionLoanInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 3,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      operator: getNextAccount(),
      config: getNextAccount(),
      loan: getNextAccount(),
    },
    data: getTransitionLoanInstructionDataDecoder().decode(instruction.data),
  };
}
