/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertIsInstructionWithAccounts,
  containsBytes,
  extendClient,
  fixEncoderSize,
  getBytesEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__FAILED_TO_IDENTIFY_ACCOUNT,
  SOLANA_ERROR__PROGRAM_CLIENTS__FAILED_TO_IDENTIFY_INSTRUCTION,
  SOLANA_ERROR__PROGRAM_CLIENTS__UNRECOGNIZED_INSTRUCTION_TYPE,
  SolanaError,
  type Address,
  type ClientWithRpc,
  type ClientWithTransactionPlanning,
  type ClientWithTransactionSending,
  type ExtendedClient,
  type GetAccountInfoApi,
  type GetMultipleAccountsApi,
  type Instruction,
  type InstructionWithData,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  addSelfFetchFunctions,
  addSelfPlanAndSendFunctions,
  type SelfFetchFunctions,
  type SelfPlanAndSendFunctions,
} from "@solana/kit/program-client-core";
import {
  getAllocationCommitmentCodec,
  getBorrowerAuditCodec,
  getCheckinCommitmentCodec,
  getCommunityAuditCodec,
  getConsentCommitmentCodec,
  getEligibilityAttestationCodec,
  getLoanAccountCodec,
  getOpportunityCommitmentCodec,
  getOutcomeCommitmentCodec,
  getPaymentCommitmentCodec,
  getPlatformConfigCodec,
  getReadinessAttestationCodec,
  type AllocationCommitment,
  type AllocationCommitmentArgs,
  type BorrowerAudit,
  type BorrowerAuditArgs,
  type CheckinCommitment,
  type CheckinCommitmentArgs,
  type CommunityAudit,
  type CommunityAuditArgs,
  type ConsentCommitment,
  type ConsentCommitmentArgs,
  type EligibilityAttestation,
  type EligibilityAttestationArgs,
  type LoanAccount,
  type LoanAccountArgs,
  type OpportunityCommitment,
  type OpportunityCommitmentArgs,
  type OutcomeCommitment,
  type OutcomeCommitmentArgs,
  type PaymentCommitment,
  type PaymentCommitmentArgs,
  type PlatformConfig,
  type PlatformConfigArgs,
  type ReadinessAttestation,
  type ReadinessAttestationArgs,
} from "../accounts/index.ts";
import {
  getAnchorAllocationInstructionAsync,
  getAnchorCheckinInstructionAsync,
  getAnchorConsentInstructionAsync,
  getAnchorOpportunityInstructionAsync,
  getAnchorOutcomeInstructionAsync,
  getAnchorPaymentInstructionAsync,
  getAttestEligibilityInstructionAsync,
  getAttestReadinessInstructionAsync,
  getCreateLoanInstructionAsync,
  getInitializePlatformInstructionAsync,
  getRegisterBorrowerRefInstructionAsync,
  getRegisterCommunityInstructionAsync,
  getSetOperatorInstructionAsync,
  getTransitionLoanInstructionAsync,
  getVaultTransferInstructionAsync,
  getVerifyCommunityInstructionAsync,
  parseAnchorAllocationInstruction,
  parseAnchorCheckinInstruction,
  parseAnchorConsentInstruction,
  parseAnchorOpportunityInstruction,
  parseAnchorOutcomeInstruction,
  parseAnchorPaymentInstruction,
  parseAttestEligibilityInstruction,
  parseAttestReadinessInstruction,
  parseCreateLoanInstruction,
  parseInitializePlatformInstruction,
  parseRegisterBorrowerRefInstruction,
  parseRegisterCommunityInstruction,
  parseSetOperatorInstruction,
  parseTransitionLoanInstruction,
  parseVaultTransferInstruction,
  parseVerifyCommunityInstruction,
  type AnchorAllocationAsyncInput,
  type AnchorCheckinAsyncInput,
  type AnchorConsentAsyncInput,
  type AnchorOpportunityAsyncInput,
  type AnchorOutcomeAsyncInput,
  type AnchorPaymentAsyncInput,
  type AttestEligibilityAsyncInput,
  type AttestReadinessAsyncInput,
  type CreateLoanAsyncInput,
  type InitializePlatformAsyncInput,
  type ParsedAnchorAllocationInstruction,
  type ParsedAnchorCheckinInstruction,
  type ParsedAnchorConsentInstruction,
  type ParsedAnchorOpportunityInstruction,
  type ParsedAnchorOutcomeInstruction,
  type ParsedAnchorPaymentInstruction,
  type ParsedAttestEligibilityInstruction,
  type ParsedAttestReadinessInstruction,
  type ParsedCreateLoanInstruction,
  type ParsedInitializePlatformInstruction,
  type ParsedRegisterBorrowerRefInstruction,
  type ParsedRegisterCommunityInstruction,
  type ParsedSetOperatorInstruction,
  type ParsedTransitionLoanInstruction,
  type ParsedVaultTransferInstruction,
  type ParsedVerifyCommunityInstruction,
  type RegisterBorrowerRefAsyncInput,
  type RegisterCommunityAsyncInput,
  type SetOperatorAsyncInput,
  type TransitionLoanAsyncInput,
  type VaultTransferAsyncInput,
  type VerifyCommunityAsyncInput,
} from "../instructions/index.ts";
import {
  findAllocationPda,
  findAttestationPda,
  findBorrowerPda,
  findCheckinPda,
  findCommunityPda,
  findConfigPda,
  findConsentPda,
  findEligibilityPda,
  findLoanPda,
  findOpportunityPda,
  findOutcomePda,
  findPaymentPda,
  findVaultAuthorityPda,
} from "../pdas/index.ts";

export const EMPOWERFI_AUDIT_PROGRAM_ADDRESS =
  "4rqhxEwPiTd5CATztMfNmFfLaSntcmZPuzHKgmbESfRR" as Address<"4rqhxEwPiTd5CATztMfNmFfLaSntcmZPuzHKgmbESfRR">;

export const EmpowerfiAuditAccount = {
  0: "AllocationCommitment",
  1: "BorrowerAudit",
  2: "CheckinCommitment",
  3: "CommunityAudit",
  4: "ConsentCommitment",
  5: "EligibilityAttestation",
  6: "LoanAccount",
  7: "OpportunityCommitment",
  8: "OutcomeCommitment",
  9: "PaymentCommitment",
  10: "PlatformConfig",
  11: "ReadinessAttestation",
  AllocationCommitment: 0,
  BorrowerAudit: 1,
  CheckinCommitment: 2,
  CommunityAudit: 3,
  ConsentCommitment: 4,
  EligibilityAttestation: 5,
  LoanAccount: 6,
  OpportunityCommitment: 7,
  OutcomeCommitment: 8,
  PaymentCommitment: 9,
  PlatformConfig: 10,
  ReadinessAttestation: 11,
} as const;

export type EmpowerfiAuditAccount = (typeof EmpowerfiAuditAccount)[Exclude<
  keyof typeof EmpowerfiAuditAccount,
  number
>];

export function identifyEmpowerfiAuditAccount(
  account: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): EmpowerfiAuditAccount {
  const data = "data" in account ? account.data : account;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([64, 38, 248, 32, 30, 54, 227, 238]),
      ),
      0,
    )
  ) {
    return EmpowerfiAuditAccount.AllocationCommitment;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([103, 199, 172, 160, 205, 121, 124, 234]),
      ),
      0,
    )
  ) {
    return EmpowerfiAuditAccount.BorrowerAudit;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([146, 23, 113, 44, 66, 57, 60, 198]),
      ),
      0,
    )
  ) {
    return EmpowerfiAuditAccount.CheckinCommitment;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([84, 251, 150, 98, 114, 27, 191, 124]),
      ),
      0,
    )
  ) {
    return EmpowerfiAuditAccount.CommunityAudit;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([31, 117, 162, 52, 234, 25, 80, 87]),
      ),
      0,
    )
  ) {
    return EmpowerfiAuditAccount.ConsentCommitment;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([153, 11, 66, 237, 172, 55, 219, 62]),
      ),
      0,
    )
  ) {
    return EmpowerfiAuditAccount.EligibilityAttestation;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([223, 49, 62, 167, 247, 182, 239, 60]),
      ),
      0,
    )
  ) {
    return EmpowerfiAuditAccount.LoanAccount;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([224, 249, 17, 85, 219, 212, 30, 125]),
      ),
      0,
    )
  ) {
    return EmpowerfiAuditAccount.OpportunityCommitment;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([232, 253, 228, 116, 32, 163, 199, 180]),
      ),
      0,
    )
  ) {
    return EmpowerfiAuditAccount.OutcomeCommitment;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([131, 95, 199, 99, 47, 159, 31, 23]),
      ),
      0,
    )
  ) {
    return EmpowerfiAuditAccount.PaymentCommitment;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([160, 78, 128, 0, 248, 83, 230, 160]),
      ),
      0,
    )
  ) {
    return EmpowerfiAuditAccount.PlatformConfig;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([158, 83, 113, 34, 226, 43, 188, 147]),
      ),
      0,
    )
  ) {
    return EmpowerfiAuditAccount.ReadinessAttestation;
  }
  throw new SolanaError(
    SOLANA_ERROR__PROGRAM_CLIENTS__FAILED_TO_IDENTIFY_ACCOUNT,
    { accountData: data, programName: "empowerfiAudit" },
  );
}

export const EmpowerfiAuditInstruction = {
  0: "AnchorAllocation",
  1: "AnchorCheckin",
  2: "AnchorConsent",
  3: "AnchorOpportunity",
  4: "AnchorOutcome",
  5: "AnchorPayment",
  6: "AttestEligibility",
  7: "AttestReadiness",
  8: "CreateLoan",
  9: "InitializePlatform",
  10: "RegisterBorrowerRef",
  11: "RegisterCommunity",
  12: "SetOperator",
  13: "TransitionLoan",
  14: "VaultTransfer",
  15: "VerifyCommunity",
  AnchorAllocation: 0,
  AnchorCheckin: 1,
  AnchorConsent: 2,
  AnchorOpportunity: 3,
  AnchorOutcome: 4,
  AnchorPayment: 5,
  AttestEligibility: 6,
  AttestReadiness: 7,
  CreateLoan: 8,
  InitializePlatform: 9,
  RegisterBorrowerRef: 10,
  RegisterCommunity: 11,
  SetOperator: 12,
  TransitionLoan: 13,
  VaultTransfer: 14,
  VerifyCommunity: 15,
} as const;

export type EmpowerfiAuditInstruction =
  (typeof EmpowerfiAuditInstruction)[Exclude<
    keyof typeof EmpowerfiAuditInstruction,
    number
  >];

export function identifyEmpowerfiAuditInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): EmpowerfiAuditInstruction {
  const data = "data" in instruction ? instruction.data : instruction;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([46, 219, 30, 121, 190, 99, 183, 242]),
      ),
      0,
    )
  ) {
    return EmpowerfiAuditInstruction.AnchorAllocation;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([231, 111, 38, 124, 230, 131, 22, 219]),
      ),
      0,
    )
  ) {
    return EmpowerfiAuditInstruction.AnchorCheckin;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([184, 226, 221, 184, 204, 187, 242, 37]),
      ),
      0,
    )
  ) {
    return EmpowerfiAuditInstruction.AnchorConsent;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([181, 6, 247, 147, 168, 144, 92, 150]),
      ),
      0,
    )
  ) {
    return EmpowerfiAuditInstruction.AnchorOpportunity;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([252, 143, 166, 43, 172, 223, 25, 13]),
      ),
      0,
    )
  ) {
    return EmpowerfiAuditInstruction.AnchorOutcome;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([185, 26, 49, 155, 134, 35, 5, 167]),
      ),
      0,
    )
  ) {
    return EmpowerfiAuditInstruction.AnchorPayment;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([199, 54, 190, 133, 207, 219, 168, 98]),
      ),
      0,
    )
  ) {
    return EmpowerfiAuditInstruction.AttestEligibility;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([192, 219, 150, 110, 139, 47, 138, 18]),
      ),
      0,
    )
  ) {
    return EmpowerfiAuditInstruction.AttestReadiness;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([166, 131, 118, 219, 138, 218, 206, 140]),
      ),
      0,
    )
  ) {
    return EmpowerfiAuditInstruction.CreateLoan;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([119, 201, 101, 45, 75, 122, 89, 3]),
      ),
      0,
    )
  ) {
    return EmpowerfiAuditInstruction.InitializePlatform;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([237, 66, 168, 86, 122, 77, 249, 130]),
      ),
      0,
    )
  ) {
    return EmpowerfiAuditInstruction.RegisterBorrowerRef;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([37, 95, 179, 249, 145, 183, 247, 180]),
      ),
      0,
    )
  ) {
    return EmpowerfiAuditInstruction.RegisterCommunity;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([238, 153, 101, 169, 243, 131, 36, 1]),
      ),
      0,
    )
  ) {
    return EmpowerfiAuditInstruction.SetOperator;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([53, 30, 226, 118, 198, 154, 112, 240]),
      ),
      0,
    )
  ) {
    return EmpowerfiAuditInstruction.TransitionLoan;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([211, 125, 3, 105, 45, 33, 227, 214]),
      ),
      0,
    )
  ) {
    return EmpowerfiAuditInstruction.VaultTransfer;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([20, 199, 137, 11, 205, 181, 244, 188]),
      ),
      0,
    )
  ) {
    return EmpowerfiAuditInstruction.VerifyCommunity;
  }
  throw new SolanaError(
    SOLANA_ERROR__PROGRAM_CLIENTS__FAILED_TO_IDENTIFY_INSTRUCTION,
    { instructionData: data, programName: "empowerfiAudit" },
  );
}

export type ParsedEmpowerfiAuditInstruction<
  TProgram extends string = "4rqhxEwPiTd5CATztMfNmFfLaSntcmZPuzHKgmbESfRR",
> =
  | ({
      instructionType: typeof EmpowerfiAuditInstruction.AnchorAllocation;
    } & ParsedAnchorAllocationInstruction<TProgram>)
  | ({
      instructionType: typeof EmpowerfiAuditInstruction.AnchorCheckin;
    } & ParsedAnchorCheckinInstruction<TProgram>)
  | ({
      instructionType: typeof EmpowerfiAuditInstruction.AnchorConsent;
    } & ParsedAnchorConsentInstruction<TProgram>)
  | ({
      instructionType: typeof EmpowerfiAuditInstruction.AnchorOpportunity;
    } & ParsedAnchorOpportunityInstruction<TProgram>)
  | ({
      instructionType: typeof EmpowerfiAuditInstruction.AnchorOutcome;
    } & ParsedAnchorOutcomeInstruction<TProgram>)
  | ({
      instructionType: typeof EmpowerfiAuditInstruction.AnchorPayment;
    } & ParsedAnchorPaymentInstruction<TProgram>)
  | ({
      instructionType: typeof EmpowerfiAuditInstruction.AttestEligibility;
    } & ParsedAttestEligibilityInstruction<TProgram>)
  | ({
      instructionType: typeof EmpowerfiAuditInstruction.AttestReadiness;
    } & ParsedAttestReadinessInstruction<TProgram>)
  | ({
      instructionType: typeof EmpowerfiAuditInstruction.CreateLoan;
    } & ParsedCreateLoanInstruction<TProgram>)
  | ({
      instructionType: typeof EmpowerfiAuditInstruction.InitializePlatform;
    } & ParsedInitializePlatformInstruction<TProgram>)
  | ({
      instructionType: typeof EmpowerfiAuditInstruction.RegisterBorrowerRef;
    } & ParsedRegisterBorrowerRefInstruction<TProgram>)
  | ({
      instructionType: typeof EmpowerfiAuditInstruction.RegisterCommunity;
    } & ParsedRegisterCommunityInstruction<TProgram>)
  | ({
      instructionType: typeof EmpowerfiAuditInstruction.SetOperator;
    } & ParsedSetOperatorInstruction<TProgram>)
  | ({
      instructionType: typeof EmpowerfiAuditInstruction.TransitionLoan;
    } & ParsedTransitionLoanInstruction<TProgram>)
  | ({
      instructionType: typeof EmpowerfiAuditInstruction.VaultTransfer;
    } & ParsedVaultTransferInstruction<TProgram>)
  | ({
      instructionType: typeof EmpowerfiAuditInstruction.VerifyCommunity;
    } & ParsedVerifyCommunityInstruction<TProgram>);

export function parseEmpowerfiAuditInstruction<TProgram extends string>(
  instruction: Instruction<TProgram> & InstructionWithData<ReadonlyUint8Array>,
): ParsedEmpowerfiAuditInstruction<TProgram> {
  const instructionType = identifyEmpowerfiAuditInstruction(instruction);
  switch (instructionType) {
    case EmpowerfiAuditInstruction.AnchorAllocation: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: EmpowerfiAuditInstruction.AnchorAllocation,
        ...parseAnchorAllocationInstruction(instruction),
      };
    }
    case EmpowerfiAuditInstruction.AnchorCheckin: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: EmpowerfiAuditInstruction.AnchorCheckin,
        ...parseAnchorCheckinInstruction(instruction),
      };
    }
    case EmpowerfiAuditInstruction.AnchorConsent: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: EmpowerfiAuditInstruction.AnchorConsent,
        ...parseAnchorConsentInstruction(instruction),
      };
    }
    case EmpowerfiAuditInstruction.AnchorOpportunity: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: EmpowerfiAuditInstruction.AnchorOpportunity,
        ...parseAnchorOpportunityInstruction(instruction),
      };
    }
    case EmpowerfiAuditInstruction.AnchorOutcome: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: EmpowerfiAuditInstruction.AnchorOutcome,
        ...parseAnchorOutcomeInstruction(instruction),
      };
    }
    case EmpowerfiAuditInstruction.AnchorPayment: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: EmpowerfiAuditInstruction.AnchorPayment,
        ...parseAnchorPaymentInstruction(instruction),
      };
    }
    case EmpowerfiAuditInstruction.AttestEligibility: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: EmpowerfiAuditInstruction.AttestEligibility,
        ...parseAttestEligibilityInstruction(instruction),
      };
    }
    case EmpowerfiAuditInstruction.AttestReadiness: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: EmpowerfiAuditInstruction.AttestReadiness,
        ...parseAttestReadinessInstruction(instruction),
      };
    }
    case EmpowerfiAuditInstruction.CreateLoan: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: EmpowerfiAuditInstruction.CreateLoan,
        ...parseCreateLoanInstruction(instruction),
      };
    }
    case EmpowerfiAuditInstruction.InitializePlatform: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: EmpowerfiAuditInstruction.InitializePlatform,
        ...parseInitializePlatformInstruction(instruction),
      };
    }
    case EmpowerfiAuditInstruction.RegisterBorrowerRef: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: EmpowerfiAuditInstruction.RegisterBorrowerRef,
        ...parseRegisterBorrowerRefInstruction(instruction),
      };
    }
    case EmpowerfiAuditInstruction.RegisterCommunity: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: EmpowerfiAuditInstruction.RegisterCommunity,
        ...parseRegisterCommunityInstruction(instruction),
      };
    }
    case EmpowerfiAuditInstruction.SetOperator: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: EmpowerfiAuditInstruction.SetOperator,
        ...parseSetOperatorInstruction(instruction),
      };
    }
    case EmpowerfiAuditInstruction.TransitionLoan: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: EmpowerfiAuditInstruction.TransitionLoan,
        ...parseTransitionLoanInstruction(instruction),
      };
    }
    case EmpowerfiAuditInstruction.VaultTransfer: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: EmpowerfiAuditInstruction.VaultTransfer,
        ...parseVaultTransferInstruction(instruction),
      };
    }
    case EmpowerfiAuditInstruction.VerifyCommunity: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: EmpowerfiAuditInstruction.VerifyCommunity,
        ...parseVerifyCommunityInstruction(instruction),
      };
    }
    default:
      throw new SolanaError(
        SOLANA_ERROR__PROGRAM_CLIENTS__UNRECOGNIZED_INSTRUCTION_TYPE,
        {
          instructionType: instructionType as string,
          programName: "empowerfiAudit",
        },
      );
  }
}

export type EmpowerfiAuditPlugin = {
  accounts: EmpowerfiAuditPluginAccounts;
  instructions: EmpowerfiAuditPluginInstructions;
  pdas: EmpowerfiAuditPluginPdas;
  identifyAccount: typeof identifyEmpowerfiAuditAccount;
  identifyInstruction: typeof identifyEmpowerfiAuditInstruction;
  parseInstruction: typeof parseEmpowerfiAuditInstruction;
};

export type EmpowerfiAuditPluginAccounts = {
  allocationCommitment: ReturnType<typeof getAllocationCommitmentCodec> &
    SelfFetchFunctions<AllocationCommitmentArgs, AllocationCommitment>;
  borrowerAudit: ReturnType<typeof getBorrowerAuditCodec> &
    SelfFetchFunctions<BorrowerAuditArgs, BorrowerAudit>;
  checkinCommitment: ReturnType<typeof getCheckinCommitmentCodec> &
    SelfFetchFunctions<CheckinCommitmentArgs, CheckinCommitment>;
  communityAudit: ReturnType<typeof getCommunityAuditCodec> &
    SelfFetchFunctions<CommunityAuditArgs, CommunityAudit>;
  consentCommitment: ReturnType<typeof getConsentCommitmentCodec> &
    SelfFetchFunctions<ConsentCommitmentArgs, ConsentCommitment>;
  eligibilityAttestation: ReturnType<typeof getEligibilityAttestationCodec> &
    SelfFetchFunctions<EligibilityAttestationArgs, EligibilityAttestation>;
  loanAccount: ReturnType<typeof getLoanAccountCodec> &
    SelfFetchFunctions<LoanAccountArgs, LoanAccount>;
  opportunityCommitment: ReturnType<typeof getOpportunityCommitmentCodec> &
    SelfFetchFunctions<OpportunityCommitmentArgs, OpportunityCommitment>;
  outcomeCommitment: ReturnType<typeof getOutcomeCommitmentCodec> &
    SelfFetchFunctions<OutcomeCommitmentArgs, OutcomeCommitment>;
  paymentCommitment: ReturnType<typeof getPaymentCommitmentCodec> &
    SelfFetchFunctions<PaymentCommitmentArgs, PaymentCommitment>;
  platformConfig: ReturnType<typeof getPlatformConfigCodec> &
    SelfFetchFunctions<PlatformConfigArgs, PlatformConfig>;
  readinessAttestation: ReturnType<typeof getReadinessAttestationCodec> &
    SelfFetchFunctions<ReadinessAttestationArgs, ReadinessAttestation>;
};

export type EmpowerfiAuditPluginInstructions = {
  anchorAllocation: (
    input: AnchorAllocationAsyncInput,
  ) => ReturnType<typeof getAnchorAllocationInstructionAsync> &
    SelfPlanAndSendFunctions;
  anchorCheckin: (
    input: AnchorCheckinAsyncInput,
  ) => ReturnType<typeof getAnchorCheckinInstructionAsync> &
    SelfPlanAndSendFunctions;
  anchorConsent: (
    input: AnchorConsentAsyncInput,
  ) => ReturnType<typeof getAnchorConsentInstructionAsync> &
    SelfPlanAndSendFunctions;
  anchorOpportunity: (
    input: AnchorOpportunityAsyncInput,
  ) => ReturnType<typeof getAnchorOpportunityInstructionAsync> &
    SelfPlanAndSendFunctions;
  anchorOutcome: (
    input: AnchorOutcomeAsyncInput,
  ) => ReturnType<typeof getAnchorOutcomeInstructionAsync> &
    SelfPlanAndSendFunctions;
  anchorPayment: (
    input: AnchorPaymentAsyncInput,
  ) => ReturnType<typeof getAnchorPaymentInstructionAsync> &
    SelfPlanAndSendFunctions;
  attestEligibility: (
    input: AttestEligibilityAsyncInput,
  ) => ReturnType<typeof getAttestEligibilityInstructionAsync> &
    SelfPlanAndSendFunctions;
  attestReadiness: (
    input: AttestReadinessAsyncInput,
  ) => ReturnType<typeof getAttestReadinessInstructionAsync> &
    SelfPlanAndSendFunctions;
  createLoan: (
    input: CreateLoanAsyncInput,
  ) => ReturnType<typeof getCreateLoanInstructionAsync> &
    SelfPlanAndSendFunctions;
  initializePlatform: (
    input: InitializePlatformAsyncInput,
  ) => ReturnType<typeof getInitializePlatformInstructionAsync> &
    SelfPlanAndSendFunctions;
  registerBorrowerRef: (
    input: RegisterBorrowerRefAsyncInput,
  ) => ReturnType<typeof getRegisterBorrowerRefInstructionAsync> &
    SelfPlanAndSendFunctions;
  registerCommunity: (
    input: RegisterCommunityAsyncInput,
  ) => ReturnType<typeof getRegisterCommunityInstructionAsync> &
    SelfPlanAndSendFunctions;
  setOperator: (
    input: SetOperatorAsyncInput,
  ) => ReturnType<typeof getSetOperatorInstructionAsync> &
    SelfPlanAndSendFunctions;
  transitionLoan: (
    input: TransitionLoanAsyncInput,
  ) => ReturnType<typeof getTransitionLoanInstructionAsync> &
    SelfPlanAndSendFunctions;
  vaultTransfer: (
    input: VaultTransferAsyncInput,
  ) => ReturnType<typeof getVaultTransferInstructionAsync> &
    SelfPlanAndSendFunctions;
  verifyCommunity: (
    input: VerifyCommunityAsyncInput,
  ) => ReturnType<typeof getVerifyCommunityInstructionAsync> &
    SelfPlanAndSendFunctions;
};

export type EmpowerfiAuditPluginPdas = {
  config: typeof findConfigPda;
  allocation: typeof findAllocationPda;
  checkin: typeof findCheckinPda;
  consent: typeof findConsentPda;
  opportunity: typeof findOpportunityPda;
  outcome: typeof findOutcomePda;
  payment: typeof findPaymentPda;
  eligibility: typeof findEligibilityPda;
  attestation: typeof findAttestationPda;
  loan: typeof findLoanPda;
  borrower: typeof findBorrowerPda;
  community: typeof findCommunityPda;
  vaultAuthority: typeof findVaultAuthorityPda;
};

export type EmpowerfiAuditPluginRequirements = ClientWithRpc<
  GetAccountInfoApi & GetMultipleAccountsApi
> &
  ClientWithTransactionPlanning &
  ClientWithTransactionSending;

export function empowerfiAuditProgram() {
  return <T extends EmpowerfiAuditPluginRequirements>(
    client: T,
  ): ExtendedClient<T, { empowerfiAudit: EmpowerfiAuditPlugin }> => {
    return extendClient(client, {
      empowerfiAudit: {
        accounts: {
          allocationCommitment: addSelfFetchFunctions(
            client,
            getAllocationCommitmentCodec(),
          ),
          borrowerAudit: addSelfFetchFunctions(client, getBorrowerAuditCodec()),
          checkinCommitment: addSelfFetchFunctions(
            client,
            getCheckinCommitmentCodec(),
          ),
          communityAudit: addSelfFetchFunctions(
            client,
            getCommunityAuditCodec(),
          ),
          consentCommitment: addSelfFetchFunctions(
            client,
            getConsentCommitmentCodec(),
          ),
          eligibilityAttestation: addSelfFetchFunctions(
            client,
            getEligibilityAttestationCodec(),
          ),
          loanAccount: addSelfFetchFunctions(client, getLoanAccountCodec()),
          opportunityCommitment: addSelfFetchFunctions(
            client,
            getOpportunityCommitmentCodec(),
          ),
          outcomeCommitment: addSelfFetchFunctions(
            client,
            getOutcomeCommitmentCodec(),
          ),
          paymentCommitment: addSelfFetchFunctions(
            client,
            getPaymentCommitmentCodec(),
          ),
          platformConfig: addSelfFetchFunctions(
            client,
            getPlatformConfigCodec(),
          ),
          readinessAttestation: addSelfFetchFunctions(
            client,
            getReadinessAttestationCodec(),
          ),
        },
        instructions: {
          anchorAllocation: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getAnchorAllocationInstructionAsync(input),
            ),
          anchorCheckin: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getAnchorCheckinInstructionAsync(input),
            ),
          anchorConsent: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getAnchorConsentInstructionAsync(input),
            ),
          anchorOpportunity: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getAnchorOpportunityInstructionAsync(input),
            ),
          anchorOutcome: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getAnchorOutcomeInstructionAsync(input),
            ),
          anchorPayment: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getAnchorPaymentInstructionAsync(input),
            ),
          attestEligibility: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getAttestEligibilityInstructionAsync(input),
            ),
          attestReadiness: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getAttestReadinessInstructionAsync(input),
            ),
          createLoan: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getCreateLoanInstructionAsync(input),
            ),
          initializePlatform: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getInitializePlatformInstructionAsync(input),
            ),
          registerBorrowerRef: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getRegisterBorrowerRefInstructionAsync(input),
            ),
          registerCommunity: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getRegisterCommunityInstructionAsync(input),
            ),
          setOperator: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getSetOperatorInstructionAsync(input),
            ),
          transitionLoan: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getTransitionLoanInstructionAsync(input),
            ),
          vaultTransfer: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getVaultTransferInstructionAsync(input),
            ),
          verifyCommunity: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getVerifyCommunityInstructionAsync(input),
            ),
        },
        pdas: {
          config: findConfigPda,
          allocation: findAllocationPda,
          checkin: findCheckinPda,
          consent: findConsentPda,
          opportunity: findOpportunityPda,
          outcome: findOutcomePda,
          payment: findPaymentPda,
          eligibility: findEligibilityPda,
          attestation: findAttestationPda,
          loan: findLoanPda,
          borrower: findBorrowerPda,
          community: findCommunityPda,
          vaultAuthority: findVaultAuthorityPda,
        },
        identifyAccount: identifyEmpowerfiAuditAccount,
        identifyInstruction: identifyEmpowerfiAuditInstruction,
        parseInstruction: parseEmpowerfiAuditInstruction,
      } as EmpowerfiAuditPlugin,
    });
  };
}
