/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertIsInstructionWithAccounts,
  containsBytes,
  extendClient,
  fixEncoderSize,
  getBytesEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__FAILED_TO_IDENTIFY_ACCOUNT,
  SOLANA_ERROR__PROGRAM_CLIENTS__FAILED_TO_IDENTIFY_INSTRUCTION,
  SOLANA_ERROR__PROGRAM_CLIENTS__UNRECOGNIZED_INSTRUCTION_TYPE,
  SolanaError,
  type Address,
  type ClientWithRpc,
  type ClientWithTransactionPlanning,
  type ClientWithTransactionSending,
  type ExtendedClient,
  type GetAccountInfoApi,
  type GetMultipleAccountsApi,
  type Instruction,
  type InstructionWithData,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  addSelfFetchFunctions,
  addSelfPlanAndSendFunctions,
  type SelfFetchFunctions,
  type SelfPlanAndSendFunctions,
} from "@solana/kit/program-client-core";
import {
  getBorrowerAuditCodec,
  getCheckinCommitmentCodec,
  getCommunityAuditCodec,
  getEligibilityAttestationCodec,
  getLoanAccountCodec,
  getOpportunityCommitmentCodec,
  getPaymentCommitmentCodec,
  getPlatformConfigCodec,
  getReadinessAttestationCodec,
  type BorrowerAudit,
  type BorrowerAuditArgs,
  type CheckinCommitment,
  type CheckinCommitmentArgs,
  type CommunityAudit,
  type CommunityAuditArgs,
  type EligibilityAttestation,
  type EligibilityAttestationArgs,
  type LoanAccount,
  type LoanAccountArgs,
  type OpportunityCommitment,
  type OpportunityCommitmentArgs,
  type PaymentCommitment,
  type PaymentCommitmentArgs,
  type PlatformConfig,
  type PlatformConfigArgs,
  type ReadinessAttestation,
  type ReadinessAttestationArgs,
} from "../accounts/index.ts";
import {
  getAnchorCheckinInstructionAsync,
  getAnchorOpportunityInstructionAsync,
  getAnchorPaymentInstructionAsync,
  getAttestEligibilityInstructionAsync,
  getAttestReadinessInstructionAsync,
  getCreateLoanInstructionAsync,
  getInitializePlatformInstructionAsync,
  getRegisterBorrowerRefInstructionAsync,
  getRegisterCommunityInstructionAsync,
  getSetOperatorInstructionAsync,
  getTransitionLoanInstructionAsync,
  getVerifyCommunityInstructionAsync,
  parseAnchorCheckinInstruction,
  parseAnchorOpportunityInstruction,
  parseAnchorPaymentInstruction,
  parseAttestEligibilityInstruction,
  parseAttestReadinessInstruction,
  parseCreateLoanInstruction,
  parseInitializePlatformInstruction,
  parseRegisterBorrowerRefInstruction,
  parseRegisterCommunityInstruction,
  parseSetOperatorInstruction,
  parseTransitionLoanInstruction,
  parseVerifyCommunityInstruction,
  type AnchorCheckinAsyncInput,
  type AnchorOpportunityAsyncInput,
  type AnchorPaymentAsyncInput,
  type AttestEligibilityAsyncInput,
  type AttestReadinessAsyncInput,
  type CreateLoanAsyncInput,
  type InitializePlatformAsyncInput,
  type ParsedAnchorCheckinInstruction,
  type ParsedAnchorOpportunityInstruction,
  type ParsedAnchorPaymentInstruction,
  type ParsedAttestEligibilityInstruction,
  type ParsedAttestReadinessInstruction,
  type ParsedCreateLoanInstruction,
  type ParsedInitializePlatformInstruction,
  type ParsedRegisterBorrowerRefInstruction,
  type ParsedRegisterCommunityInstruction,
  type ParsedSetOperatorInstruction,
  type ParsedTransitionLoanInstruction,
  type ParsedVerifyCommunityInstruction,
  type RegisterBorrowerRefAsyncInput,
  type RegisterCommunityAsyncInput,
  type SetOperatorAsyncInput,
  type TransitionLoanAsyncInput,
  type VerifyCommunityAsyncInput,
} from "../instructions/index.ts";
import {
  findAttestationPda,
  findBorrowerPda,
  findCheckinPda,
  findCommunityPda,
  findConfigPda,
  findEligibilityPda,
  findLoanPda,
  findOpportunityPda,
  findPaymentPda,
} from "../pdas/index.ts";

export const EMPOWERFI_AUDIT_PROGRAM_ADDRESS =
  "4rqhxEwPiTd5CATztMfNmFfLaSntcmZPuzHKgmbESfRR" as Address<"4rqhxEwPiTd5CATztMfNmFfLaSntcmZPuzHKgmbESfRR">;

export const EmpowerfiAuditAccount = {
  0: "BorrowerAudit",
  1: "CheckinCommitment",
  2: "CommunityAudit",
  3: "EligibilityAttestation",
  4: "LoanAccount",
  5: "OpportunityCommitment",
  6: "PaymentCommitment",
  7: "PlatformConfig",
  8: "ReadinessAttestation",
  BorrowerAudit: 0,
  CheckinCommitment: 1,
  CommunityAudit: 2,
  EligibilityAttestation: 3,
  LoanAccount: 4,
  OpportunityCommitment: 5,
  PaymentCommitment: 6,
  PlatformConfig: 7,
  ReadinessAttestation: 8,
} as const;

export type EmpowerfiAuditAccount = (typeof EmpowerfiAuditAccount)[Exclude<
  keyof typeof EmpowerfiAuditAccount,
  number
>];

export function identifyEmpowerfiAuditAccount(
  account: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): EmpowerfiAuditAccount {
  const data = "data" in account ? account.data : account;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([103, 199, 172, 160, 205, 121, 124, 234]),
      ),
      0,
    )
  ) {
    return EmpowerfiAuditAccount.BorrowerAudit;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([146, 23, 113, 44, 66, 57, 60, 198]),
      ),
      0,
    )
  ) {
    return EmpowerfiAuditAccount.CheckinCommitment;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([84, 251, 150, 98, 114, 27, 191, 124]),
      ),
      0,
    )
  ) {
    return EmpowerfiAuditAccount.CommunityAudit;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([153, 11, 66, 237, 172, 55, 219, 62]),
      ),
      0,
    )
  ) {
    return EmpowerfiAuditAccount.EligibilityAttestation;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([223, 49, 62, 167, 247, 182, 239, 60]),
      ),
      0,
    )
  ) {
    return EmpowerfiAuditAccount.LoanAccount;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([224, 249, 17, 85, 219, 212, 30, 125]),
      ),
      0,
    )
  ) {
    return EmpowerfiAuditAccount.OpportunityCommitment;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([131, 95, 199, 99, 47, 159, 31, 23]),
      ),
      0,
    )
  ) {
    return EmpowerfiAuditAccount.PaymentCommitment;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([160, 78, 128, 0, 248, 83, 230, 160]),
      ),
      0,
    )
  ) {
    return EmpowerfiAuditAccount.PlatformConfig;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([158, 83, 113, 34, 226, 43, 188, 147]),
      ),
      0,
    )
  ) {
    return EmpowerfiAuditAccount.ReadinessAttestation;
  }
  throw new SolanaError(
    SOLANA_ERROR__PROGRAM_CLIENTS__FAILED_TO_IDENTIFY_ACCOUNT,
    { accountData: data, programName: "empowerfiAudit" },
  );
}

export const EmpowerfiAuditInstruction = {
  0: "AnchorCheckin",
  1: "AnchorOpportunity",
  2: "AnchorPayment",
  3: "AttestEligibility",
  4: "AttestReadiness",
  5: "CreateLoan",
  6: "InitializePlatform",
  7: "RegisterBorrowerRef",
  8: "RegisterCommunity",
  9: "SetOperator",
  10: "TransitionLoan",
  11: "VerifyCommunity",
  AnchorCheckin: 0,
  AnchorOpportunity: 1,
  AnchorPayment: 2,
  AttestEligibility: 3,
  AttestReadiness: 4,
  CreateLoan: 5,
  InitializePlatform: 6,
  RegisterBorrowerRef: 7,
  RegisterCommunity: 8,
  SetOperator: 9,
  TransitionLoan: 10,
  VerifyCommunity: 11,
} as const;

export type EmpowerfiAuditInstruction =
  (typeof EmpowerfiAuditInstruction)[Exclude<
    keyof typeof EmpowerfiAuditInstruction,
    number
  >];

export function identifyEmpowerfiAuditInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): EmpowerfiAuditInstruction {
  const data = "data" in instruction ? instruction.data : instruction;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([231, 111, 38, 124, 230, 131, 22, 219]),
      ),
      0,
    )
  ) {
    return EmpowerfiAuditInstruction.AnchorCheckin;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([181, 6, 247, 147, 168, 144, 92, 150]),
      ),
      0,
    )
  ) {
    return EmpowerfiAuditInstruction.AnchorOpportunity;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([185, 26, 49, 155, 134, 35, 5, 167]),
      ),
      0,
    )
  ) {
    return EmpowerfiAuditInstruction.AnchorPayment;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([199, 54, 190, 133, 207, 219, 168, 98]),
      ),
      0,
    )
  ) {
    return EmpowerfiAuditInstruction.AttestEligibility;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([192, 219, 150, 110, 139, 47, 138, 18]),
      ),
      0,
    )
  ) {
    return EmpowerfiAuditInstruction.AttestReadiness;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([166, 131, 118, 219, 138, 218, 206, 140]),
      ),
      0,
    )
  ) {
    return EmpowerfiAuditInstruction.CreateLoan;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([119, 201, 101, 45, 75, 122, 89, 3]),
      ),
      0,
    )
  ) {
    return EmpowerfiAuditInstruction.InitializePlatform;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([237, 66, 168, 86, 122, 77, 249, 130]),
      ),
      0,
    )
  ) {
    return EmpowerfiAuditInstruction.RegisterBorrowerRef;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([37, 95, 179, 249, 145, 183, 247, 180]),
      ),
      0,
    )
  ) {
    return EmpowerfiAuditInstruction.RegisterCommunity;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([238, 153, 101, 169, 243, 131, 36, 1]),
      ),
      0,
    )
  ) {
    return EmpowerfiAuditInstruction.SetOperator;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([53, 30, 226, 118, 198, 154, 112, 240]),
      ),
      0,
    )
  ) {
    return EmpowerfiAuditInstruction.TransitionLoan;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([20, 199, 137, 11, 205, 181, 244, 188]),
      ),
      0,
    )
  ) {
    return EmpowerfiAuditInstruction.VerifyCommunity;
  }
  throw new SolanaError(
    SOLANA_ERROR__PROGRAM_CLIENTS__FAILED_TO_IDENTIFY_INSTRUCTION,
    { instructionData: data, programName: "empowerfiAudit" },
  );
}

export type ParsedEmpowerfiAuditInstruction<
  TProgram extends string = "4rqhxEwPiTd5CATztMfNmFfLaSntcmZPuzHKgmbESfRR",
> =
  | ({
      instructionType: typeof EmpowerfiAuditInstruction.AnchorCheckin;
    } & ParsedAnchorCheckinInstruction<TProgram>)
  | ({
      instructionType: typeof EmpowerfiAuditInstruction.AnchorOpportunity;
    } & ParsedAnchorOpportunityInstruction<TProgram>)
  | ({
      instructionType: typeof EmpowerfiAuditInstruction.AnchorPayment;
    } & ParsedAnchorPaymentInstruction<TProgram>)
  | ({
      instructionType: typeof EmpowerfiAuditInstruction.AttestEligibility;
    } & ParsedAttestEligibilityInstruction<TProgram>)
  | ({
      instructionType: typeof EmpowerfiAuditInstruction.AttestReadiness;
    } & ParsedAttestReadinessInstruction<TProgram>)
  | ({
      instructionType: typeof EmpowerfiAuditInstruction.CreateLoan;
    } & ParsedCreateLoanInstruction<TProgram>)
  | ({
      instructionType: typeof EmpowerfiAuditInstruction.InitializePlatform;
    } & ParsedInitializePlatformInstruction<TProgram>)
  | ({
      instructionType: typeof EmpowerfiAuditInstruction.RegisterBorrowerRef;
    } & ParsedRegisterBorrowerRefInstruction<TProgram>)
  | ({
      instructionType: typeof EmpowerfiAuditInstruction.RegisterCommunity;
    } & ParsedRegisterCommunityInstruction<TProgram>)
  | ({
      instructionType: typeof EmpowerfiAuditInstruction.SetOperator;
    } & ParsedSetOperatorInstruction<TProgram>)
  | ({
      instructionType: typeof EmpowerfiAuditInstruction.TransitionLoan;
    } & ParsedTransitionLoanInstruction<TProgram>)
  | ({
      instructionType: typeof EmpowerfiAuditInstruction.VerifyCommunity;
    } & ParsedVerifyCommunityInstruction<TProgram>);

export function parseEmpowerfiAuditInstruction<TProgram extends string>(
  instruction: Instruction<TProgram> & InstructionWithData<ReadonlyUint8Array>,
): ParsedEmpowerfiAuditInstruction<TProgram> {
  const instructionType = identifyEmpowerfiAuditInstruction(instruction);
  switch (instructionType) {
    case EmpowerfiAuditInstruction.AnchorCheckin: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: EmpowerfiAuditInstruction.AnchorCheckin,
        ...parseAnchorCheckinInstruction(instruction),
      };
    }
    case EmpowerfiAuditInstruction.AnchorOpportunity: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: EmpowerfiAuditInstruction.AnchorOpportunity,
        ...parseAnchorOpportunityInstruction(instruction),
      };
    }
    case EmpowerfiAuditInstruction.AnchorPayment: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: EmpowerfiAuditInstruction.AnchorPayment,
        ...parseAnchorPaymentInstruction(instruction),
      };
    }
    case EmpowerfiAuditInstruction.AttestEligibility: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: EmpowerfiAuditInstruction.AttestEligibility,
        ...parseAttestEligibilityInstruction(instruction),
      };
    }
    case EmpowerfiAuditInstruction.AttestReadiness: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: EmpowerfiAuditInstruction.AttestReadiness,
        ...parseAttestReadinessInstruction(instruction),
      };
    }
    case EmpowerfiAuditInstruction.CreateLoan: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: EmpowerfiAuditInstruction.CreateLoan,
        ...parseCreateLoanInstruction(instruction),
      };
    }
    case EmpowerfiAuditInstruction.InitializePlatform: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: EmpowerfiAuditInstruction.InitializePlatform,
        ...parseInitializePlatformInstruction(instruction),
      };
    }
    case EmpowerfiAuditInstruction.RegisterBorrowerRef: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: EmpowerfiAuditInstruction.RegisterBorrowerRef,
        ...parseRegisterBorrowerRefInstruction(instruction),
      };
    }
    case EmpowerfiAuditInstruction.RegisterCommunity: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: EmpowerfiAuditInstruction.RegisterCommunity,
        ...parseRegisterCommunityInstruction(instruction),
      };
    }
    case EmpowerfiAuditInstruction.SetOperator: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: EmpowerfiAuditInstruction.SetOperator,
        ...parseSetOperatorInstruction(instruction),
      };
    }
    case EmpowerfiAuditInstruction.TransitionLoan: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: EmpowerfiAuditInstruction.TransitionLoan,
        ...parseTransitionLoanInstruction(instruction),
      };
    }
    case EmpowerfiAuditInstruction.VerifyCommunity: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: EmpowerfiAuditInstruction.VerifyCommunity,
        ...parseVerifyCommunityInstruction(instruction),
      };
    }
    default:
      throw new SolanaError(
        SOLANA_ERROR__PROGRAM_CLIENTS__UNRECOGNIZED_INSTRUCTION_TYPE,
        {
          instructionType: instructionType as string,
          programName: "empowerfiAudit",
        },
      );
  }
}

export type EmpowerfiAuditPlugin = {
  accounts: EmpowerfiAuditPluginAccounts;
  instructions: EmpowerfiAuditPluginInstructions;
  pdas: EmpowerfiAuditPluginPdas;
  identifyAccount: typeof identifyEmpowerfiAuditAccount;
  identifyInstruction: typeof identifyEmpowerfiAuditInstruction;
  parseInstruction: typeof parseEmpowerfiAuditInstruction;
};

export type EmpowerfiAuditPluginAccounts = {
  borrowerAudit: ReturnType<typeof getBorrowerAuditCodec> &
    SelfFetchFunctions<BorrowerAuditArgs, BorrowerAudit>;
  checkinCommitment: ReturnType<typeof getCheckinCommitmentCodec> &
    SelfFetchFunctions<CheckinCommitmentArgs, CheckinCommitment>;
  communityAudit: ReturnType<typeof getCommunityAuditCodec> &
    SelfFetchFunctions<CommunityAuditArgs, CommunityAudit>;
  eligibilityAttestation: ReturnType<typeof getEligibilityAttestationCodec> &
    SelfFetchFunctions<EligibilityAttestationArgs, EligibilityAttestation>;
  loanAccount: ReturnType<typeof getLoanAccountCodec> &
    SelfFetchFunctions<LoanAccountArgs, LoanAccount>;
  opportunityCommitment: ReturnType<typeof getOpportunityCommitmentCodec> &
    SelfFetchFunctions<OpportunityCommitmentArgs, OpportunityCommitment>;
  paymentCommitment: ReturnType<typeof getPaymentCommitmentCodec> &
    SelfFetchFunctions<PaymentCommitmentArgs, PaymentCommitment>;
  platformConfig: ReturnType<typeof getPlatformConfigCodec> &
    SelfFetchFunctions<PlatformConfigArgs, PlatformConfig>;
  readinessAttestation: ReturnType<typeof getReadinessAttestationCodec> &
    SelfFetchFunctions<ReadinessAttestationArgs, ReadinessAttestation>;
};

export type EmpowerfiAuditPluginInstructions = {
  anchorCheckin: (
    input: AnchorCheckinAsyncInput,
  ) => ReturnType<typeof getAnchorCheckinInstructionAsync> &
    SelfPlanAndSendFunctions;
  anchorOpportunity: (
    input: AnchorOpportunityAsyncInput,
  ) => ReturnType<typeof getAnchorOpportunityInstructionAsync> &
    SelfPlanAndSendFunctions;
  anchorPayment: (
    input: AnchorPaymentAsyncInput,
  ) => ReturnType<typeof getAnchorPaymentInstructionAsync> &
    SelfPlanAndSendFunctions;
  attestEligibility: (
    input: AttestEligibilityAsyncInput,
  ) => ReturnType<typeof getAttestEligibilityInstructionAsync> &
    SelfPlanAndSendFunctions;
  attestReadiness: (
    input: AttestReadinessAsyncInput,
  ) => ReturnType<typeof getAttestReadinessInstructionAsync> &
    SelfPlanAndSendFunctions;
  createLoan: (
    input: CreateLoanAsyncInput,
  ) => ReturnType<typeof getCreateLoanInstructionAsync> &
    SelfPlanAndSendFunctions;
  initializePlatform: (
    input: InitializePlatformAsyncInput,
  ) => ReturnType<typeof getInitializePlatformInstructionAsync> &
    SelfPlanAndSendFunctions;
  registerBorrowerRef: (
    input: RegisterBorrowerRefAsyncInput,
  ) => ReturnType<typeof getRegisterBorrowerRefInstructionAsync> &
    SelfPlanAndSendFunctions;
  registerCommunity: (
    input: RegisterCommunityAsyncInput,
  ) => ReturnType<typeof getRegisterCommunityInstructionAsync> &
    SelfPlanAndSendFunctions;
  setOperator: (
    input: SetOperatorAsyncInput,
  ) => ReturnType<typeof getSetOperatorInstructionAsync> &
    SelfPlanAndSendFunctions;
  transitionLoan: (
    input: TransitionLoanAsyncInput,
  ) => ReturnType<typeof getTransitionLoanInstructionAsync> &
    SelfPlanAndSendFunctions;
  verifyCommunity: (
    input: VerifyCommunityAsyncInput,
  ) => ReturnType<typeof getVerifyCommunityInstructionAsync> &
    SelfPlanAndSendFunctions;
};

export type EmpowerfiAuditPluginPdas = {
  config: typeof findConfigPda;
  checkin: typeof findCheckinPda;
  opportunity: typeof findOpportunityPda;
  payment: typeof findPaymentPda;
  eligibility: typeof findEligibilityPda;
  attestation: typeof findAttestationPda;
  loan: typeof findLoanPda;
  borrower: typeof findBorrowerPda;
  community: typeof findCommunityPda;
};

export type EmpowerfiAuditPluginRequirements = ClientWithRpc<
  GetAccountInfoApi & GetMultipleAccountsApi
> &
  ClientWithTransactionPlanning &
  ClientWithTransactionSending;

export function empowerfiAuditProgram() {
  return <T extends EmpowerfiAuditPluginRequirements>(
    client: T,
  ): ExtendedClient<T, { empowerfiAudit: EmpowerfiAuditPlugin }> => {
    return extendClient(client, {
      empowerfiAudit: {
        accounts: {
          borrowerAudit: addSelfFetchFunctions(client, getBorrowerAuditCodec()),
          checkinCommitment: addSelfFetchFunctions(
            client,
            getCheckinCommitmentCodec(),
          ),
          communityAudit: addSelfFetchFunctions(
            client,
            getCommunityAuditCodec(),
          ),
          eligibilityAttestation: addSelfFetchFunctions(
            client,
            getEligibilityAttestationCodec(),
          ),
          loanAccount: addSelfFetchFunctions(client, getLoanAccountCodec()),
          opportunityCommitment: addSelfFetchFunctions(
            client,
            getOpportunityCommitmentCodec(),
          ),
          paymentCommitment: addSelfFetchFunctions(
            client,
            getPaymentCommitmentCodec(),
          ),
          platformConfig: addSelfFetchFunctions(
            client,
            getPlatformConfigCodec(),
          ),
          readinessAttestation: addSelfFetchFunctions(
            client,
            getReadinessAttestationCodec(),
          ),
        },
        instructions: {
          anchorCheckin: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getAnchorCheckinInstructionAsync(input),
            ),
          anchorOpportunity: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getAnchorOpportunityInstructionAsync(input),
            ),
          anchorPayment: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getAnchorPaymentInstructionAsync(input),
            ),
          attestEligibility: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getAttestEligibilityInstructionAsync(input),
            ),
          attestReadiness: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getAttestReadinessInstructionAsync(input),
            ),
          createLoan: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getCreateLoanInstructionAsync(input),
            ),
          initializePlatform: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getInitializePlatformInstructionAsync(input),
            ),
          registerBorrowerRef: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getRegisterBorrowerRefInstructionAsync(input),
            ),
          registerCommunity: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getRegisterCommunityInstructionAsync(input),
            ),
          setOperator: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getSetOperatorInstructionAsync(input),
            ),
          transitionLoan: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getTransitionLoanInstructionAsync(input),
            ),
          verifyCommunity: (input) =>
            addSelfPlanAndSendFunctions(
              client,
              getVerifyCommunityInstructionAsync(input),
            ),
        },
        pdas: {
          config: findConfigPda,
          checkin: findCheckinPda,
          opportunity: findOpportunityPda,
          payment: findPaymentPda,
          eligibility: findEligibilityPda,
          attestation: findAttestationPda,
          loan: findLoanPda,
          borrower: findBorrowerPda,
          community: findCommunityPda,
        },
        identifyAccount: identifyEmpowerfiAuditAccount,
        identifyInstruction: identifyEmpowerfiAuditInstruction,
        parseInstruction: parseEmpowerfiAuditInstruction,
      } as EmpowerfiAuditPlugin,
    });
  };
}
