/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  getAddressEncoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getU32Encoder,
  type Address,
  type ProgramDerivedAddress,
} from "@solana/kit";

export type AttestationSeeds = {
  borrower: Address;
  assessmentNo: number;
};

export async function findAttestationPda(
  seeds: AttestationSeeds,
  config: { programAddress?: Address | undefined } = {},
): Promise<ProgramDerivedAddress> {
  const {
    programAddress = "4rqhxEwPiTd5CATztMfNmFfLaSntcmZPuzHKgmbESfRR" as Address<"4rqhxEwPiTd5CATztMfNmFfLaSntcmZPuzHKgmbESfRR">,
  } = config;
  return await getProgramDerivedAddress({
    programAddress,
    seeds: [
      getBytesEncoder().encode(
        new Uint8Array([114, 101, 97, 100, 105, 110, 101, 115, 115]),
      ),
      getAddressEncoder().encode(seeds.borrower),
      getU32Encoder().encode(seeds.assessmentNo),
    ],
  });
}
