/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  fixEncoderSize,
  getBytesEncoder,
  getProgramDerivedAddress,
  type Address,
  type ProgramDerivedAddress,
  type ReadonlyUint8Array,
} from "@solana/kit";

export type BorrowerSeeds = {
  borrowerRefHash: ReadonlyUint8Array;
};

export async function findBorrowerPda(
  seeds: BorrowerSeeds,
  config: { programAddress?: Address | undefined } = {},
): Promise<ProgramDerivedAddress> {
  const {
    programAddress = "4rqhxEwPiTd5CATztMfNmFfLaSntcmZPuzHKgmbESfRR" as Address<"4rqhxEwPiTd5CATztMfNmFfLaSntcmZPuzHKgmbESfRR">,
  } = config;
  return await getProgramDerivedAddress({
    programAddress,
    seeds: [
      getBytesEncoder().encode(
        new Uint8Array([98, 111, 114, 114, 111, 119, 101, 114]),
      ),
      fixEncoderSize(getBytesEncoder(), 32).encode(seeds.borrowerRefHash),
    ],
  });
}
