/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  getAddressEncoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getU16Encoder,
  type Address,
  type ProgramDerivedAddress,
} from "@solana/kit";

export type PaymentSeeds = {
  loan: Address;
  instalmentNo: number;
};

export async function findPaymentPda(
  seeds: PaymentSeeds,
  config: { programAddress?: Address | undefined } = {},
): Promise<ProgramDerivedAddress> {
  const {
    programAddress = "4rqhxEwPiTd5CATztMfNmFfLaSntcmZPuzHKgmbESfRR" as Address<"4rqhxEwPiTd5CATztMfNmFfLaSntcmZPuzHKgmbESfRR">,
  } = config;
  return await getProgramDerivedAddress({
    programAddress,
    seeds: [
      getBytesEncoder().encode(
        new Uint8Array([112, 97, 121, 109, 101, 110, 116]),
      ),
      getAddressEncoder().encode(seeds.loan),
      getU16Encoder().encode(seeds.instalmentNo),
    ],
  });
}
