/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  getAddressEncoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  type Address,
  type ProgramDerivedAddress,
} from "@solana/kit";

export type SettlementRouteSeeds = {
  loan: Address;
};

export async function findSettlementRoutePda(
  seeds: SettlementRouteSeeds,
  config: { programAddress?: Address | undefined } = {},
): Promise<ProgramDerivedAddress> {
  const {
    programAddress = "4rqhxEwPiTd5CATztMfNmFfLaSntcmZPuzHKgmbESfRR" as Address<"4rqhxEwPiTd5CATztMfNmFfLaSntcmZPuzHKgmbESfRR">,
  } = config;
  return await getProgramDerivedAddress({
    programAddress,
    seeds: [
      getBytesEncoder().encode(
        new Uint8Array([
          115, 101, 116, 116, 108, 101, 109, 101, 110, 116, 95, 114, 111, 117,
          116, 101,
        ]),
      ),
      getAddressEncoder().encode(seeds.loan),
    ],
  });
}
