/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";

export const ALLOCATION_COMMITMENT_DISCRIMINATOR: ReadonlyUint8Array =
  new Uint8Array([64, 38, 248, 32, 30, 54, 227, 238]);

export function getAllocationCommitmentDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    ALLOCATION_COMMITMENT_DISCRIMINATOR,
  );
}

export type AllocationCommitment = {
  discriminator: ReadonlyUint8Array;
  allocationRefHash: ReadonlyUint8Array;
  commitment: ReadonlyUint8Array;
  allocatedAt: bigint;
  schemaVersion: number;
  bump: number;
};

export type AllocationCommitmentArgs = {
  allocationRefHash: ReadonlyUint8Array;
  commitment: ReadonlyUint8Array;
  allocatedAt: number | bigint;
  schemaVersion: number;
  bump: number;
};

/** Gets the encoder for {@link AllocationCommitmentArgs} account data. */
export function getAllocationCommitmentEncoder(): FixedSizeEncoder<AllocationCommitmentArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["allocationRefHash", fixEncoderSize(getBytesEncoder(), 32)],
      ["commitment", fixEncoderSize(getBytesEncoder(), 32)],
      ["allocatedAt", getI64Encoder()],
      ["schemaVersion", getU8Encoder()],
      ["bump", getU8Encoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: ALLOCATION_COMMITMENT_DISCRIMINATOR,
    }),
  );
}

/** Gets the decoder for {@link AllocationCommitment} account data. */
export function getAllocationCommitmentDecoder(): FixedSizeDecoder<AllocationCommitment> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["allocationRefHash", fixDecoderSize(getBytesDecoder(), 32)],
    ["commitment", fixDecoderSize(getBytesDecoder(), 32)],
    ["allocatedAt", getI64Decoder()],
    ["schemaVersion", getU8Decoder()],
    ["bump", getU8Decoder()],
  ]);
}

/** Gets the codec for {@link AllocationCommitment} account data. */
export function getAllocationCommitmentCodec(): FixedSizeCodec<
  AllocationCommitmentArgs,
  AllocationCommitment
> {
  return combineCodec(
    getAllocationCommitmentEncoder(),
    getAllocationCommitmentDecoder(),
  );
}

export function decodeAllocationCommitment<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<AllocationCommitment, TAddress>;
export function decodeAllocationCommitment<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<AllocationCommitment, TAddress>;
export function decodeAllocationCommitment<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
):
  | Account<AllocationCommitment, TAddress>
  | MaybeAccount<AllocationCommitment, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getAllocationCommitmentDecoder(),
  );
}

export async function fetchAllocationCommitment<
  TAddress extends string = string,
>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<AllocationCommitment, TAddress>> {
  const maybeAccount = await fetchMaybeAllocationCommitment(
    rpc,
    address,
    config,
  );
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeAllocationCommitment<
  TAddress extends string = string,
>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<AllocationCommitment, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeAllocationCommitment(maybeAccount);
}

export async function fetchAllAllocationCommitment(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<AllocationCommitment>[]> {
  const maybeAccounts = await fetchAllMaybeAllocationCommitment(
    rpc,
    addresses,
    config,
  );
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeAllocationCommitment(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<AllocationCommitment>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) =>
    decodeAllocationCommitment(maybeAccount),
  );
}

export function getAllocationCommitmentSize(): number {
  return 82;
}
