/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";

export const BORROWER_AUDIT_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
  103, 199, 172, 160, 205, 121, 124, 234,
]);

export function getBorrowerAuditDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    BORROWER_AUDIT_DISCRIMINATOR,
  );
}

export type BorrowerAudit = {
  discriminator: ReadonlyUint8Array;
  borrowerRefHash: ReadonlyUint8Array;
  /** The CommunityAudit she was enrolled through. */
  community: Address;
  /** Commitment to the enrollment record (who, which community, when). */
  enrollmentCommitment: ReadonlyUint8Array;
  registeredAt: bigint;
  schemaVersion: number;
  bump: number;
};

export type BorrowerAuditArgs = {
  borrowerRefHash: ReadonlyUint8Array;
  /** The CommunityAudit she was enrolled through. */
  community: Address;
  /** Commitment to the enrollment record (who, which community, when). */
  enrollmentCommitment: ReadonlyUint8Array;
  registeredAt: number | bigint;
  schemaVersion: number;
  bump: number;
};

/** Gets the encoder for {@link BorrowerAuditArgs} account data. */
export function getBorrowerAuditEncoder(): FixedSizeEncoder<BorrowerAuditArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["borrowerRefHash", fixEncoderSize(getBytesEncoder(), 32)],
      ["community", getAddressEncoder()],
      ["enrollmentCommitment", fixEncoderSize(getBytesEncoder(), 32)],
      ["registeredAt", getI64Encoder()],
      ["schemaVersion", getU8Encoder()],
      ["bump", getU8Encoder()],
    ]),
    (value) => ({ ...value, discriminator: BORROWER_AUDIT_DISCRIMINATOR }),
  );
}

/** Gets the decoder for {@link BorrowerAudit} account data. */
export function getBorrowerAuditDecoder(): FixedSizeDecoder<BorrowerAudit> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["borrowerRefHash", fixDecoderSize(getBytesDecoder(), 32)],
    ["community", getAddressDecoder()],
    ["enrollmentCommitment", fixDecoderSize(getBytesDecoder(), 32)],
    ["registeredAt", getI64Decoder()],
    ["schemaVersion", getU8Decoder()],
    ["bump", getU8Decoder()],
  ]);
}

/** Gets the codec for {@link BorrowerAudit} account data. */
export function getBorrowerAuditCodec(): FixedSizeCodec<
  BorrowerAuditArgs,
  BorrowerAudit
> {
  return combineCodec(getBorrowerAuditEncoder(), getBorrowerAuditDecoder());
}

export function decodeBorrowerAudit<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<BorrowerAudit, TAddress>;
export function decodeBorrowerAudit<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<BorrowerAudit, TAddress>;
export function decodeBorrowerAudit<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
): Account<BorrowerAudit, TAddress> | MaybeAccount<BorrowerAudit, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getBorrowerAuditDecoder(),
  );
}

export async function fetchBorrowerAudit<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<BorrowerAudit, TAddress>> {
  const maybeAccount = await fetchMaybeBorrowerAudit(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeBorrowerAudit<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<BorrowerAudit, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeBorrowerAudit(maybeAccount);
}

export async function fetchAllBorrowerAudit(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<BorrowerAudit>[]> {
  const maybeAccounts = await fetchAllMaybeBorrowerAudit(
    rpc,
    addresses,
    config,
  );
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeBorrowerAudit(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<BorrowerAudit>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeBorrowerAudit(maybeAccount));
}

export function getBorrowerAuditSize(): number {
  return 114;
}
