/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  getCommunityStatusDecoder,
  getCommunityStatusEncoder,
  type CommunityStatus,
  type CommunityStatusArgs,
} from "../types/index.ts";

export const COMMUNITY_AUDIT_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array(
  [84, 251, 150, 98, 114, 27, 191, 124],
);

export function getCommunityAuditDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    COMMUNITY_AUDIT_DISCRIMINATOR,
  );
}

export type CommunityAudit = {
  discriminator: ReadonlyUint8Array;
  communityRef: ReadonlyUint8Array;
  /** Commitment to the community's canonical record at registration. */
  commitment: ReadonlyUint8Array;
  status: CommunityStatus;
  /** Commitment to the verification record; zero until verified. */
  verificationCommitment: ReadonlyUint8Array;
  registeredAt: bigint;
  /** Zero until verified. */
  verifiedAt: bigint;
  schemaVersion: number;
  bump: number;
};

export type CommunityAuditArgs = {
  communityRef: ReadonlyUint8Array;
  /** Commitment to the community's canonical record at registration. */
  commitment: ReadonlyUint8Array;
  status: CommunityStatusArgs;
  /** Commitment to the verification record; zero until verified. */
  verificationCommitment: ReadonlyUint8Array;
  registeredAt: number | bigint;
  /** Zero until verified. */
  verifiedAt: number | bigint;
  schemaVersion: number;
  bump: number;
};

/** Gets the encoder for {@link CommunityAuditArgs} account data. */
export function getCommunityAuditEncoder(): FixedSizeEncoder<CommunityAuditArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["communityRef", fixEncoderSize(getBytesEncoder(), 32)],
      ["commitment", fixEncoderSize(getBytesEncoder(), 32)],
      ["status", getCommunityStatusEncoder()],
      ["verificationCommitment", fixEncoderSize(getBytesEncoder(), 32)],
      ["registeredAt", getI64Encoder()],
      ["verifiedAt", getI64Encoder()],
      ["schemaVersion", getU8Encoder()],
      ["bump", getU8Encoder()],
    ]),
    (value) => ({ ...value, discriminator: COMMUNITY_AUDIT_DISCRIMINATOR }),
  );
}

/** Gets the decoder for {@link CommunityAudit} account data. */
export function getCommunityAuditDecoder(): FixedSizeDecoder<CommunityAudit> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["communityRef", fixDecoderSize(getBytesDecoder(), 32)],
    ["commitment", fixDecoderSize(getBytesDecoder(), 32)],
    ["status", getCommunityStatusDecoder()],
    ["verificationCommitment", fixDecoderSize(getBytesDecoder(), 32)],
    ["registeredAt", getI64Decoder()],
    ["verifiedAt", getI64Decoder()],
    ["schemaVersion", getU8Decoder()],
    ["bump", getU8Decoder()],
  ]);
}

/** Gets the codec for {@link CommunityAudit} account data. */
export function getCommunityAuditCodec(): FixedSizeCodec<
  CommunityAuditArgs,
  CommunityAudit
> {
  return combineCodec(getCommunityAuditEncoder(), getCommunityAuditDecoder());
}

export function decodeCommunityAudit<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<CommunityAudit, TAddress>;
export function decodeCommunityAudit<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<CommunityAudit, TAddress>;
export function decodeCommunityAudit<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
): Account<CommunityAudit, TAddress> | MaybeAccount<CommunityAudit, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getCommunityAuditDecoder(),
  );
}

export async function fetchCommunityAudit<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<CommunityAudit, TAddress>> {
  const maybeAccount = await fetchMaybeCommunityAudit(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeCommunityAudit<
  TAddress extends string = string,
>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<CommunityAudit, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeCommunityAudit(maybeAccount);
}

export async function fetchAllCommunityAudit(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<CommunityAudit>[]> {
  const maybeAccounts = await fetchAllMaybeCommunityAudit(
    rpc,
    addresses,
    config,
  );
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeCommunityAudit(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<CommunityAudit>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) =>
    decodeCommunityAudit(maybeAccount),
  );
}

export function getCommunityAuditSize(): number {
  return 123;
}
