/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  getLoanStatusDecoder,
  getLoanStatusEncoder,
  type LoanStatus,
  type LoanStatusArgs,
} from "../types/index.ts";

export const LOAN_ACCOUNT_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
  223, 49, 62, 167, 247, 182, 239, 60,
]);

export function getLoanAccountDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    LOAN_ACCOUNT_DISCRIMINATOR,
  );
}

export type LoanAccount = {
  discriminator: ReadonlyUint8Array;
  borrower: Address;
  opportunity: Address;
  status: LoanStatus;
  termsCommitment: ReadonlyUint8Array;
  /** Commitment to the record behind the latest status change. */
  lastTransitionCommitment: ReadonlyUint8Array;
  transitions: number;
  createdAt: bigint;
  updatedAt: bigint;
  schemaVersion: number;
  bump: number;
};

export type LoanAccountArgs = {
  borrower: Address;
  opportunity: Address;
  status: LoanStatusArgs;
  termsCommitment: ReadonlyUint8Array;
  /** Commitment to the record behind the latest status change. */
  lastTransitionCommitment: ReadonlyUint8Array;
  transitions: number;
  createdAt: number | bigint;
  updatedAt: number | bigint;
  schemaVersion: number;
  bump: number;
};

/** Gets the encoder for {@link LoanAccountArgs} account data. */
export function getLoanAccountEncoder(): FixedSizeEncoder<LoanAccountArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["borrower", getAddressEncoder()],
      ["opportunity", getAddressEncoder()],
      ["status", getLoanStatusEncoder()],
      ["termsCommitment", fixEncoderSize(getBytesEncoder(), 32)],
      ["lastTransitionCommitment", fixEncoderSize(getBytesEncoder(), 32)],
      ["transitions", getU16Encoder()],
      ["createdAt", getI64Encoder()],
      ["updatedAt", getI64Encoder()],
      ["schemaVersion", getU8Encoder()],
      ["bump", getU8Encoder()],
    ]),
    (value) => ({ ...value, discriminator: LOAN_ACCOUNT_DISCRIMINATOR }),
  );
}

/** Gets the decoder for {@link LoanAccount} account data. */
export function getLoanAccountDecoder(): FixedSizeDecoder<LoanAccount> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["borrower", getAddressDecoder()],
    ["opportunity", getAddressDecoder()],
    ["status", getLoanStatusDecoder()],
    ["termsCommitment", fixDecoderSize(getBytesDecoder(), 32)],
    ["lastTransitionCommitment", fixDecoderSize(getBytesDecoder(), 32)],
    ["transitions", getU16Decoder()],
    ["createdAt", getI64Decoder()],
    ["updatedAt", getI64Decoder()],
    ["schemaVersion", getU8Decoder()],
    ["bump", getU8Decoder()],
  ]);
}

/** Gets the codec for {@link LoanAccount} account data. */
export function getLoanAccountCodec(): FixedSizeCodec<
  LoanAccountArgs,
  LoanAccount
> {
  return combineCodec(getLoanAccountEncoder(), getLoanAccountDecoder());
}

export function decodeLoanAccount<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<LoanAccount, TAddress>;
export function decodeLoanAccount<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<LoanAccount, TAddress>;
export function decodeLoanAccount<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
): Account<LoanAccount, TAddress> | MaybeAccount<LoanAccount, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getLoanAccountDecoder(),
  );
}

export async function fetchLoanAccount<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<LoanAccount, TAddress>> {
  const maybeAccount = await fetchMaybeLoanAccount(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeLoanAccount<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<LoanAccount, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeLoanAccount(maybeAccount);
}

export async function fetchAllLoanAccount(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<LoanAccount>[]> {
  const maybeAccounts = await fetchAllMaybeLoanAccount(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeLoanAccount(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<LoanAccount>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeLoanAccount(maybeAccount));
}

export function getLoanAccountSize(): number {
  return 157;
}
