/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";

export const PAYMENT_COMMITMENT_DISCRIMINATOR: ReadonlyUint8Array =
  new Uint8Array([131, 95, 199, 99, 47, 159, 31, 23]);

export function getPaymentCommitmentDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    PAYMENT_COMMITMENT_DISCRIMINATOR,
  );
}

export type PaymentCommitment = {
  discriminator: ReadonlyUint8Array;
  loan: Address;
  instalmentNo: number;
  commitment: ReadonlyUint8Array;
  recordedAt: bigint;
  schemaVersion: number;
  bump: number;
};

export type PaymentCommitmentArgs = {
  loan: Address;
  instalmentNo: number;
  commitment: ReadonlyUint8Array;
  recordedAt: number | bigint;
  schemaVersion: number;
  bump: number;
};

/** Gets the encoder for {@link PaymentCommitmentArgs} account data. */
export function getPaymentCommitmentEncoder(): FixedSizeEncoder<PaymentCommitmentArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["loan", getAddressEncoder()],
      ["instalmentNo", getU16Encoder()],
      ["commitment", fixEncoderSize(getBytesEncoder(), 32)],
      ["recordedAt", getI64Encoder()],
      ["schemaVersion", getU8Encoder()],
      ["bump", getU8Encoder()],
    ]),
    (value) => ({ ...value, discriminator: PAYMENT_COMMITMENT_DISCRIMINATOR }),
  );
}

/** Gets the decoder for {@link PaymentCommitment} account data. */
export function getPaymentCommitmentDecoder(): FixedSizeDecoder<PaymentCommitment> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["loan", getAddressDecoder()],
    ["instalmentNo", getU16Decoder()],
    ["commitment", fixDecoderSize(getBytesDecoder(), 32)],
    ["recordedAt", getI64Decoder()],
    ["schemaVersion", getU8Decoder()],
    ["bump", getU8Decoder()],
  ]);
}

/** Gets the codec for {@link PaymentCommitment} account data. */
export function getPaymentCommitmentCodec(): FixedSizeCodec<
  PaymentCommitmentArgs,
  PaymentCommitment
> {
  return combineCodec(
    getPaymentCommitmentEncoder(),
    getPaymentCommitmentDecoder(),
  );
}

export function decodePaymentCommitment<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<PaymentCommitment, TAddress>;
export function decodePaymentCommitment<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<PaymentCommitment, TAddress>;
export function decodePaymentCommitment<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
):
  | Account<PaymentCommitment, TAddress>
  | MaybeAccount<PaymentCommitment, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getPaymentCommitmentDecoder(),
  );
}

export async function fetchPaymentCommitment<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<PaymentCommitment, TAddress>> {
  const maybeAccount = await fetchMaybePaymentCommitment(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybePaymentCommitment<
  TAddress extends string = string,
>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<PaymentCommitment, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodePaymentCommitment(maybeAccount);
}

export async function fetchAllPaymentCommitment(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<PaymentCommitment>[]> {
  const maybeAccounts = await fetchAllMaybePaymentCommitment(
    rpc,
    addresses,
    config,
  );
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybePaymentCommitment(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<PaymentCommitment>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) =>
    decodePaymentCommitment(maybeAccount),
  );
}

export function getPaymentCommitmentSize(): number {
  return 84;
}
