/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU32Decoder,
  getU32Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  getReadinessBandDecoder,
  getReadinessBandEncoder,
  getReadinessStatusDecoder,
  getReadinessStatusEncoder,
  type ReadinessBand,
  type ReadinessBandArgs,
  type ReadinessStatus,
  type ReadinessStatusArgs,
} from "../types/index.ts";

export const READINESS_ATTESTATION_DISCRIMINATOR: ReadonlyUint8Array =
  new Uint8Array([158, 83, 113, 34, 226, 43, 188, 147]);

export function getReadinessAttestationDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    READINESS_ATTESTATION_DISCRIMINATOR,
  );
}

export type ReadinessAttestation = {
  discriminator: ReadonlyUint8Array;
  borrower: Address;
  /** 1, 2, 3 … per borrower. Part of the address. */
  assessmentNo: number;
  status: ReadinessStatus;
  band: ReadinessBand;
  /** major * 10000 + minor * 100 + patch: readiness-v0.1.0 is 100. */
  modelVersion: number;
  commitment: ReadonlyUint8Array;
  attestedAt: bigint;
  schemaVersion: number;
  bump: number;
};

export type ReadinessAttestationArgs = {
  borrower: Address;
  /** 1, 2, 3 … per borrower. Part of the address. */
  assessmentNo: number;
  status: ReadinessStatusArgs;
  band: ReadinessBandArgs;
  /** major * 10000 + minor * 100 + patch: readiness-v0.1.0 is 100. */
  modelVersion: number;
  commitment: ReadonlyUint8Array;
  attestedAt: number | bigint;
  schemaVersion: number;
  bump: number;
};

/** Gets the encoder for {@link ReadinessAttestationArgs} account data. */
export function getReadinessAttestationEncoder(): FixedSizeEncoder<ReadinessAttestationArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["borrower", getAddressEncoder()],
      ["assessmentNo", getU32Encoder()],
      ["status", getReadinessStatusEncoder()],
      ["band", getReadinessBandEncoder()],
      ["modelVersion", getU16Encoder()],
      ["commitment", fixEncoderSize(getBytesEncoder(), 32)],
      ["attestedAt", getI64Encoder()],
      ["schemaVersion", getU8Encoder()],
      ["bump", getU8Encoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: READINESS_ATTESTATION_DISCRIMINATOR,
    }),
  );
}

/** Gets the decoder for {@link ReadinessAttestation} account data. */
export function getReadinessAttestationDecoder(): FixedSizeDecoder<ReadinessAttestation> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["borrower", getAddressDecoder()],
    ["assessmentNo", getU32Decoder()],
    ["status", getReadinessStatusDecoder()],
    ["band", getReadinessBandDecoder()],
    ["modelVersion", getU16Decoder()],
    ["commitment", fixDecoderSize(getBytesDecoder(), 32)],
    ["attestedAt", getI64Decoder()],
    ["schemaVersion", getU8Decoder()],
    ["bump", getU8Decoder()],
  ]);
}

/** Gets the codec for {@link ReadinessAttestation} account data. */
export function getReadinessAttestationCodec(): FixedSizeCodec<
  ReadinessAttestationArgs,
  ReadinessAttestation
> {
  return combineCodec(
    getReadinessAttestationEncoder(),
    getReadinessAttestationDecoder(),
  );
}

export function decodeReadinessAttestation<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<ReadinessAttestation, TAddress>;
export function decodeReadinessAttestation<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<ReadinessAttestation, TAddress>;
export function decodeReadinessAttestation<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
):
  | Account<ReadinessAttestation, TAddress>
  | MaybeAccount<ReadinessAttestation, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getReadinessAttestationDecoder(),
  );
}

export async function fetchReadinessAttestation<
  TAddress extends string = string,
>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<ReadinessAttestation, TAddress>> {
  const maybeAccount = await fetchMaybeReadinessAttestation(
    rpc,
    address,
    config,
  );
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeReadinessAttestation<
  TAddress extends string = string,
>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<ReadinessAttestation, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeReadinessAttestation(maybeAccount);
}

export async function fetchAllReadinessAttestation(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<ReadinessAttestation>[]> {
  const maybeAccounts = await fetchAllMaybeReadinessAttestation(
    rpc,
    addresses,
    config,
  );
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeReadinessAttestation(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<ReadinessAttestation>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) =>
    decodeReadinessAttestation(maybeAccount),
  );
}

export function getReadinessAttestationSize(): number {
  return 90;
}
