// Recomputes every network vector's expectation from the TypeScript engine, and
// regenerates the pgTAP block that holds the SQL engine to the same answers.
//
//   npx tsx scripts/regenerate-network-vectors.mts
//
// The JSON is the single source: TS reads it, SQL is generated from it, and the
// two cannot drift without one of them failing. Inputs are hand-written;
// expectations are never hand-edited, because an expectation somebody typed is
// an expectation that agrees with whatever it was typed from.
import { readFileSync, writeFileSync } from "node:fs";
import { matchCapital, type CapitalNeed, type CapitalPlan, type Instrument } from "../packages/capital-allocation/src/network";

const VECTORS = "packages/capital-allocation/vectors/network.json";
const TEST = "platform/supabase/tests/capital_network.test.sql";

interface Scenario {
  name: string;
  input: { instruments: string[]; overrides?: Record<string, Partial<Instrument>>; need: CapitalNeed };
  expect?: unknown;
}
interface File { model_version: string; note: string; instruments: Instrument[]; scenarios: Scenario[] }

const file = JSON.parse(readFileSync(VECTORS, "utf8")) as File;
const byId = new Map(file.instruments.map((i) => [i.id, i]));

const used = (s: Scenario): Instrument[] =>
  s.input.instruments.map((id) => ({ ...byId.get(id)!, ...(s.input.overrides?.[id] ?? {}) }));

const expectationOf = (plan: CapitalPlan) => ({
  status: plan.status,
  reason_codes: plan.reason_codes,
  allocations: plan.allocations,
  domestic_coverage_cents: plan.domestic_coverage_cents,
  global_coverage_cents: plan.global_coverage_cents,
  unfunded_cents: plan.unfunded_cents,
  external_capital_gap_cents: plan.external_capital_gap_cents,
  eligible: plan.evaluated.filter((e) => e.eligible).map((e) => e.instrument_id),
  fit_scores: Object.fromEntries(plan.evaluated.map((e) => [e.instrument_id, e.fit_score])),
});

for (const s of file.scenarios) s.expect = expectationOf(matchCapital(s.input.need, used(s)));
writeFileSync(VECTORS, `${JSON.stringify(file, null, 2)}\n`);

// ---- the pgTAP mirror, one assertion per scenario, rebuilt whole.
const q = (s: string) => s.replace(/'/g, "''");
const assertion = (s: Scenario) => `select is(
  (select jsonb_build_object(
     'status', p -> 'status', 'reason_codes', p -> 'reason_codes', 'allocations', p -> 'allocations',
     'domestic_coverage_cents', p -> 'domestic_coverage_cents', 'global_coverage_cents', p -> 'global_coverage_cents',
     'unfunded_cents', p -> 'unfunded_cents', 'external_capital_gap_cents', p -> 'external_capital_gap_cents',
     'eligible', coalesce((select jsonb_agg(e -> 'instrument_id') from jsonb_array_elements(p -> 'evaluated') as t(e)
                           where (e ->> 'eligible')::boolean), '[]'::jsonb),
     'fit_scores', (select jsonb_object_agg(e ->> 'instrument_id', e -> 'fit_score')
                    from jsonb_array_elements(p -> 'evaluated') as t(e)))
   from (select private.match_capital(
     '${q(JSON.stringify(s.input.need))}'::jsonb,
     '${q(JSON.stringify(used(s)))}'::jsonb) as p) q),
  '${q(JSON.stringify(s.expect))}'::jsonb,
  'vector: ${q(s.name)}'
);`;

const sql = readFileSync(TEST, "utf8");
const open = "-- ------------------------------------------------------------------ the vectors";
const close = "-- ------------------------------------------------------------- the engine's run";
const a = sql.indexOf(open);
const b = sql.indexOf(close);
if (a < 0 || b < 0 || b < a) throw new Error("could not find the vector block's two ends");

const header = `${open}
-- Generated by scripts/regenerate-network-vectors.mts from
-- packages/capital-allocation/vectors/network.json. Do not edit by hand: the
-- package's own tests hold the TypeScript engine to the same expectations, so
-- the browser and the database give one answer about a capital plan.

`;
const block = `${header}${file.scenarios.map(assertion).join("\n\n")}\n\n`;
const next = sql.slice(0, a) + block + sql.slice(b);

// The plan count moves with the number of scenarios.
const before = (sql.slice(a, b).match(/^select is\(/gm) ?? []).length;
const planned = Number(/select plan\((\d+)\);/.exec(next)![1]);
const out = next.replace(/select plan\(\d+\);/, `select plan(${planned - before + file.scenarios.length});`);
writeFileSync(TEST, out);

console.log(`${file.scenarios.length} scenarios · pgTAP assertions ${before} → ${file.scenarios.length} · plan ${planned} → ${planned - before + file.scenarios.length}`);
for (const s of file.scenarios) {
  const e = s.expect as { reason_codes: string[] };
  const fresh = e.reason_codes.filter((r) => r.startsWith("LOCAL_") || r.startsWith("TERRITORIAL_") || r === "EXTERNAL_GAP_EXISTS" || r === "GLOBAL_ADDITIONALITY");
  console.log(`  ${fresh.length ? fresh.join(", ") : "—"}  ·  ${s.name.slice(0, 62)}`);
}
