/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export const ReadinessStatus = {
  0: "CreditReady",
  1: "NeedsMoreData",
  2: "NeedsPreparation",
  3: "ManualReview",
  CreditReady: 0,
  NeedsMoreData: 1,
  NeedsPreparation: 2,
  ManualReview: 3,
} as const;

export type ReadinessStatus = (typeof ReadinessStatus)[Exclude<
  keyof typeof ReadinessStatus,
  number
>];

export type ReadinessStatusArgs = ReadinessStatus;

export function getReadinessStatusEncoder(): FixedSizeEncoder<ReadinessStatusArgs> {
  return getEnumEncoder(ReadinessStatus);
}

export function getReadinessStatusDecoder(): FixedSizeDecoder<ReadinessStatus> {
  return getEnumDecoder(
    ReadinessStatus as Omit<typeof ReadinessStatus, number>,
  );
}

export function getReadinessStatusCodec(): FixedSizeCodec<
  ReadinessStatusArgs,
  ReadinessStatus
> {
  return combineCodec(getReadinessStatusEncoder(), getReadinessStatusDecoder());
}
