/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export const ReadinessBand = {
  0: "Low",
  1: "Medium",
  2: "High",
  Low: 0,
  Medium: 1,
  High: 2,
} as const;

export type ReadinessBand = (typeof ReadinessBand)[Exclude<
  keyof typeof ReadinessBand,
  number
>];

export type ReadinessBandArgs = ReadinessBand;

export function getReadinessBandEncoder(): FixedSizeEncoder<ReadinessBandArgs> {
  return getEnumEncoder(ReadinessBand);
}

export function getReadinessBandDecoder(): FixedSizeDecoder<ReadinessBand> {
  return getEnumDecoder(ReadinessBand as Omit<typeof ReadinessBand, number>);
}

export function getReadinessBandCodec(): FixedSizeCodec<
  ReadinessBandArgs,
  ReadinessBand
> {
  return combineCodec(getReadinessBandEncoder(), getReadinessBandDecoder());
}
