/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

/**
 * Which way a global loan's dollars became her reais. The two the comparator
 * weighs, and nothing about a provider, an amount or a person: the economics
 * live in the commitment, and the record behind it in the database.
 */
export const SettlementRoute = {
  0: "DirectUsdcPix",
  1: "BrlStablePix",
  DirectUsdcPix: 0,
  BrlStablePix: 1,
} as const;

/**
 * Which way a global loan's dollars became her reais. The two the comparator
 * weighs, and nothing about a provider, an amount or a person: the economics
 * live in the commitment, and the record behind it in the database.
 */
export type SettlementRoute = (typeof SettlementRoute)[Exclude<
  keyof typeof SettlementRoute,
  number
>];

export type SettlementRouteArgs = SettlementRoute;

export function getSettlementRouteEncoder(): FixedSizeEncoder<SettlementRouteArgs> {
  return getEnumEncoder(SettlementRoute);
}

export function getSettlementRouteDecoder(): FixedSizeDecoder<SettlementRoute> {
  return getEnumDecoder(
    SettlementRoute as Omit<typeof SettlementRoute, number>,
  );
}

export function getSettlementRouteCodec(): FixedSizeCodec<
  SettlementRouteArgs,
  SettlementRoute
> {
  return combineCodec(getSettlementRouteEncoder(), getSettlementRouteDecoder());
}
